#!/bin/sh

cd QGD; wclean; wcleanLnIncludeAll; cd ../

cd QGDFoam; ./Allwclean; cd ../

cd QHDFoam; ./Allwclean; cd ../

cd TQGDFoam; ./Allwclean; cd ../

cd cQGDFoam; ./Allwclean; cd ../

cd vQGDFoam; ./Allwclean; cd ../

cd utils/selectBadCells; wclean; cd ../../

#
#END-OF-FILE
#

