#!/bin/sh

cd QGD; wmake libso; cd ../

cd QGDFoam; ./Allwmake; cd ../

cd QHDFoam; ./Allwmake; cd ../

cd mulesQHDFoam; ./Allwmake; cd ../

cd utils/selectBadCells; wmake; cd ../../

#
#END-OF-FILE
#


