#!/bin/sh

cd QGD; wclean; wcleanLnIncludeAll; cd ../

cd QGDFoam; ./Allwclean; cd ../

cd mQGDFoam; ./Allwclean; cd ../

cd sQGDFoam; ./Allwclean; cd ../

cd vQGDFoam; ./Allwclean; cd ../

#
#END-OF-FILE
#

