#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
cleanSamples

if [[ -f total.log ]]; then
    rm total.log
fi

if [[ -f failed.txt ]]; then
    rm failed.txt
fi

if [[ -f successful.txt ]]; then
    rm successful.txt
fi

if [[ -f EndCalculations.end ]]; then
    rm EndCalculations.end
fi

#------------------------------------------------------------------------------
