QGDsolver: leastSquaresOpt Class Reference
leastSquaresOpt Class Reference
Classes
class extendedFaceStencilFormVfValues
Function for filling of array which contain which will contain the cells necessary for use by several processors. Source file extendedFaceStencilScalarDer.C extendedFaceStencilScalarGradOpt.C leastSquaresStencilOpt.C.
class extendedFaceStencilScalarDer
Methods for optimal calculating of directional derivative. With parallel realisation.
class extendedFaceStencilScalarGradOpt
Methods for optimal calculating of directional derivative. With parallel realisation.
class leastSquaresStencilOpt
Methods for optimal calculating of directional derivative. With parallel realisation.
Public Member Functions
TypeName ("leastSquaresOpt")
leastSquaresOpt (const IOobject &)
Construct from IOobject. Optional flag for if IOobject is the.
~leastSquaresOpt ()
Destructor.
tmp< surfaceVectorField > Grad (const volScalarField &iF)
Calculate gradient of volume scalar function on the faces.
tmp< surfaceVectorField > Grad (const volScalarField &iF, const surfaceScalarField &)
tmp< surfaceTensorField > Grad (const volVectorField &iVF)
tmp< surfaceTensorField > Grad (const volVectorField &iVF, const surfaceVectorField &)
Calculate gradient of volume vector field on the faces.
tmp< surfaceScalarField > Div (const volVectorField &iVF)
Calculate divergence of volume vector field on the faces.
tmp< surfaceVectorField > Div (const volTensorField &iTF)
Calculate divergence of volume tensor field on the faces.
Public Member Functions inherited from leastSquaresBase
leastSquaresBase (const fvMesh &mesh)
~leastSquaresBase ()
Protected Member Functions
void faceScalarDer (const Field< scalar > &iF, const Field< scalar > &sF, int com, surfaceScalarField &rField)
void faceScalarDer (const tmp< Field< scalar >> &tiF, const tmp< Field< scalar >> &tsF, int com, tmp< surfaceScalarField > &trField)
void faceScalarDer (const List3< scalar > &procVfValues, const surfaceScalarField &sF, int derComp, surfaceScalarField &rField)
void faceScalarDer (const tmp< List3< scalar >> &tprocVfValues, const tmp< surfaceScalarField > &tsF, int derComp, tmp< surfaceScalarField > &trField)
void formVfValues (const volScalarField &iF, List3< scalar > &procVfValues)
template<class FieldType >
void formVfValues (const GeometricField< FieldType, fvPatchField, volMesh > &iF, List< List3< scalar >> &procVfValues)
Protected Member Functions inherited from leastSquaresBase
void findNeighbours ()
Find neighbour cells for each face (throught face points).
void calculateWeights ()
Compute weights for least squares scheme for gradient calculation.
Additional Inherited Members
Protected Types inherited from leastSquaresBase
template<class T >
using List2 = List< List< T > >
template<class T >
using List3 = List2< List< T > >
template<class T >
using labelHashTable = HashTable< T, label, Hash< label >>
typedef HashSet< label, Hash
< label > > labelHashSet
template<class T >
using Triple = FixedList< T, 3 >
Protected Attributes inherited from leastSquaresBase
labelListList neighbourCells_
List2< vector > GdfAll_
List2< scalar > wf2All_
DynamicList< label > internalDegFaces_
List< label > procPairs_
List< label > neigProcs_
labelHashTable< label > idProcPatchPairs_
label nProcPatches_
List3< vector > procGdf_
List3< scalar > procWf2_
List3< label > myProcPatchCells_
List2< label > ownEnd_
List2< label > neiStart_
List2< label > neiEnd_
List2< label > corStart_
List2< label > corEnd_
labelHashTable< List< label > > pointCells_
labelHashTable< label > cellProc_
List2< Triple< label > > corAddr_
List2< label > corCellIds_
labelHashTable< label > corProcIds_
List< DynamicList< label > > procDegFaces_
Detailed Description
Definition at line 53 of file leastSquaresStencilOpt.H.
Constructor & Destructor Documentation
leastSquaresOpt (const IOobject & io)
Construct from IOobject. Optional flag for if IOobject is the.
top level regIOobject.
Definition at line 54 of file leastSquaresStencilOpt.C.
~leastSquaresOpt ()
Destructor.
Definition at line 62 of file leastSquaresStencilOpt.C.
Member Function Documentation
void faceScalarDer (const Field< scalar > & iF, const Field< scalar > & sF, int com, surfaceScalarField & rField) protected
Definition at line 32 of file extendedFaceStencilScalarDer.C.
References forAll(), and leastSquaresBase::GdfAll_.
void faceScalarDer (const tmp< Field< scalar >> & tiF, const tmp< Field< scalar >> & tsF, int com, tmp< surfaceScalarField > & trField) protected
Definition at line 45 of file extendedFaceStencilScalarDer.C.
References leastSquaresBase::GdfAll_, leastSquaresBase::neighbourCells_, and leastSquaresBase::wf2All_.
void faceScalarDer (const List3< scalar > & procVfValues, const surfaceScalarField & sF, int derComp, surfaceScalarField & rField) protected
Definition at line 50 of file extendedFaceStencilScalarDer.C.
void faceScalarDer (const tmp< List3< scalar >> & tprocVfValues, const tmp< surfaceScalarField > & tsF, int derComp, tmp< surfaceScalarField > & trField) protected
Definition at line 77 of file extendedFaceStencilScalarDer.C.
void formVfValues (const volScalarField & iF, List3< scalar > & procVfValues) inline protected
Definition at line 29 of file leastSquaresStencilOpt.H.
void formVfValues (const GeometricField< FieldType, fvPatchField, volMesh > & iF, List< List3< scalar >> & procVfValues) inline protected
Definition at line 145 of file leastSquaresStencilOpt.H.
TypeName ("leastSquaresOpt")
Foam::tmp< Foam::surfaceVectorField > Grad (const volScalarField & iF)
Calculate gradient of volume scalar function on the faces.
Parameters
iF Internal scalar field. Allowable values: constant reference to the volScalarField.
Returns
Gradient of iF (vector field) which was computed on the faces of mesh.
Definition at line 48 of file extendedFaceStencilScalarGradOpt.C.
Foam::tmp< Foam::surfaceVectorField > Grad (const volScalarField & iF, const surfaceScalarField & sF)
Definition at line 55 of file extendedFaceStencilScalarGradOpt.C.
Foam::tmp< Foam::surfaceTensorField > Grad (const volVectorField & iVF)
Definition at line 66 of file leastSquaresStencilOpt.C.
Foam::tmp< Foam::surfaceTensorField > Grad (const volVectorField & iVF, const surfaceVectorField & sVF)
Calculate gradient of volume vector field on the faces.
Parameters
iVF Internal vector field. Allowable values: constant reference to the volVectorField.
Returns
Gradient of iVF (tensor field) which was computed on the faces of mesh.
Definition at line 80 of file leastSquaresStencilOpt.C.
References forAll(), formVfValues(), mesh_, and nf_.
Foam::tmp< Foam::surfaceScalarField > Div (const volVectorField & iVF)
Calculate divergence of volume vector field on the faces.
Parameters
iVF Internal vector field. Allowable values: constant reference to the volVectorField.
Returns
Divergence of iVF (scalar field) which was computed on the faces of mesh.
Definition at line 186 of file leastSquaresStencilOpt.C.
References forAll(), formVfValues(), mesh_, and nf_.
Foam::tmp< Foam::surfaceVectorField > Div (const volTensorField & iTF)
Calculate divergence of volume tensor field on the faces.
Parameters
iTF Internal tensor field. Allowable values: constant reference to the volTensorField.
Returns
Divergence of iTF (vector field) which was computed on the faces of mesh.
Definition at line 256 of file leastSquaresStencilOpt.C.
The documentation for this class was generated from the following files:
QGD/fvsc/leastSquaresOpt/leastSquaresStencilOpt.H
QGD/fvsc/leastSquaresOpt/extendedFaceStencilFormVfValues.H
QGD/fvsc/leastSquaresOpt/extendedFaceStencilScalarDer.C
QGD/fvsc/leastSquaresOpt/extendedFaceStencilScalarGradOpt.C
QGD/fvsc/leastSquaresOpt/leastSquaresStencilOpt.C