QGDsolver: QGD/fvsc/leastSquaresOpt/extendedFaceStencilFormVfValues.H File Reference
extendedFaceStencilFormVfValues.H File Reference
Functions
void formVfValues (const volScalarField &iF, List3< scalar > &procVfValues)
template<class FieldType >
void formVfValues (const GeometricField< FieldType, fvPatchField, volMesh > &iF, List< List3< scalar >> &procVfValues)
Detailed Description
Original source file extendedFaceStencilFormVfValues.H
Definition in file extendedFaceStencilFormVfValues.H.
Function Documentation
void formVfValues (const volScalarField & iF, List3< scalar > & procVfValues)
Definition at line 28 of file extendedFaceStencilFormVfValues.H.
References forAll().
Referenced by leastSquaresOpt::Div(), and leastSquaresOpt::Grad().
void formVfValues (const GeometricField< FieldType, fvPatchField, volMesh > & iF, List< List3< scalar >> & procVfValues)
Definition at line 144 of file extendedFaceStencilFormVfValues.H.