QGDsolver: Foam Namespace Reference
Foam Namespace Reference
Namespaces
fvsc
qgd
Classes
class cosVelocityFvPatchVectorField
This boundary condition sets the pressure gradient to the provided value such that the flux on the boundary is that specified by the velocity boundary condition.
class qgdFluxFvPatchScalarField
This boundary condition sets the pressure gradient to the provided value such that the flux on the boundary is that specified by the velocity boundary condition.
class qhdFluxFvPatchScalarField
This boundary condition sets the pressure gradient to the provided value such that the flux on the boundary is that specified by the velocity boundary condition.
class powerLawTransport
Constant properties Transport package. Templated into a given thermodynamics package (needed for thermal conductivity).
class psiQGDReactionThermo
Foam::psiQGDReactionThermo.
class hePsiQGDThermo
Energy for a perfect gas mixture with QGD equations.
class psiQGDThermo
Class describing thermophysical properties of perfect gas with motion governed by Quasi- Gas dynamics equations.
class QGDThermo
Abstract base class for classes implementing thermophysical properties of gases and fluids governed by regularized equations (QGD & QHD)
class heRhoQGDThermo
class rhoQGDThermo
Basic thermodynamic properties based on density.
class mQhdFluxFvPatchScalarField
This boundary condition sets the pressure gradient to the provided value such that the flux on the boundary is that specified by the velocity boundary condition.
class qInterfaceProperties
Contains the interface properties.
class constTwoPhaseProperties
class twoPhaseIcoQGDThermo
Thermodynamics and mechanics class for incompressible two-phase mixture of immiscible components.
class fvsc
Methods calculating of differential operators.
class heRhoThermo
Energy for a mixture based on density.
class twoPhaseConstTau
Class for one of possible ways of tau calculating.
Typedefs
typedef List< face > faceList
Functions
makeChemistryModel (psiQGDReactionThermo)
makeChemistryModelType (StandardChemistryModel, psiQGDReactionThermo, constGasEThermoPhysics)
makeChemistryModelType (StandardChemistryModel, psiQGDReactionThermo, gasEThermoPhysics)
makeChemistryModelType (StandardChemistryModel, psiQGDReactionThermo, constIncompressibleGasEThermoPhysics)
makeChemistryModelType (StandardChemistryModel, psiQGDReactionThermo, incompressibleGasEThermoPhysics)
makeChemistryModelType (StandardChemistryModel, psiQGDReactionThermo, icoPoly8EThermoPhysics)
makeChemistryModelType (StandardChemistryModel, psiQGDReactionThermo, constFluidEThermoPhysics)
makeChemistryModelType (StandardChemistryModel, psiQGDReactionThermo, constAdiabaticFluidEThermoPhysics)
makeChemistryModelType (StandardChemistryModel, psiQGDReactionThermo, constEThermoPhysics)
makeChemistryModelType (TDACChemistryModel, psiQGDReactionThermo, constGasEThermoPhysics)
makeChemistryModelType (TDACChemistryModel, psiQGDReactionThermo, gasEThermoPhysics)
makeChemistryModelType (TDACChemistryModel, psiQGDReactionThermo, constIncompressibleGasEThermoPhysics)
makeChemistryModelType (TDACChemistryModel, psiQGDReactionThermo, incompressibleGasEThermoPhysics)
makeChemistryModelType (TDACChemistryModel, psiQGDReactionThermo, icoPoly8EThermoPhysics)
makeChemistryModelType (TDACChemistryModel, psiQGDReactionThermo, constFluidEThermoPhysics)
makeChemistryModelType (TDACChemistryModel, psiQGDReactionThermo, constAdiabaticFluidEThermoPhysics)
makeChemistryModelType (TDACChemistryModel, psiQGDReactionThermo, constEThermoPhysics)
makeChemistryReductionMethods (psiQGDReactionThermo, constGasHThermoPhysics)
makeChemistryReductionMethods (psiQGDReactionThermo, gasHThermoPhysics)
makeChemistryReductionMethods (psiQGDReactionThermo, constIncompressibleGasHThermoPhysics)
makeChemistryReductionMethods (psiQGDReactionThermo, incompressibleGasHThermoPhysics)
makeChemistryReductionMethods (psiQGDReactionThermo, icoPoly8HThermoPhysics)
makeChemistryReductionMethods (psiQGDReactionThermo, constFluidHThermoPhysics)
makeChemistryReductionMethods (psiQGDReactionThermo, constAdiabaticFluidHThermoPhysics)
makeChemistryReductionMethods (psiQGDReactionThermo, constHThermoPhysics)
makeChemistryReductionMethods (psiQGDReactionThermo, constGasEThermoPhysics)
makeChemistryReductionMethods (psiQGDReactionThermo, gasEThermoPhysics)
makeChemistryReductionMethods (psiQGDReactionThermo, constIncompressibleGasEThermoPhysics)
makeChemistryReductionMethods (psiQGDReactionThermo, incompressibleGasEThermoPhysics)
makeChemistryReductionMethods (psiQGDReactionThermo, icoPoly8EThermoPhysics)
makeChemistryReductionMethods (psiQGDReactionThermo, constFluidEThermoPhysics)
makeChemistryReductionMethods (psiQGDReactionThermo, constAdiabaticFluidEThermoPhysics)
makeChemistryReductionMethods (psiQGDReactionThermo, constEThermoPhysics)
makeChemistryTabulationMethods (psiQGDReactionThermo, constGasHThermoPhysics)
makeChemistryTabulationMethods (psiQGDReactionThermo, gasHThermoPhysics)
makeChemistryTabulationMethods (psiQGDReactionThermo, constIncompressibleGasHThermoPhysics)
makeChemistryTabulationMethods (psiQGDReactionThermo, incompressibleGasHThermoPhysics)
makeChemistryTabulationMethods (psiQGDReactionThermo, icoPoly8HThermoPhysics)
makeChemistryTabulationMethods (psiQGDReactionThermo, constFluidHThermoPhysics)
makeChemistryTabulationMethods (psiQGDReactionThermo, constAdiabaticFluidHThermoPhysics)
makeChemistryTabulationMethods (psiQGDReactionThermo, constHThermoPhysics)
makeChemistryTabulationMethods (psiQGDReactionThermo, constGasEThermoPhysics)
makeChemistryTabulationMethods (psiQGDReactionThermo, gasEThermoPhysics)
makeChemistryTabulationMethods (psiQGDReactionThermo, constIncompressibleGasEThermoPhysics)
makeChemistryTabulationMethods (psiQGDReactionThermo, incompressibleGasEThermoPhysics)
makeChemistryTabulationMethods (psiQGDReactionThermo, icoPoly8EThermoPhysics)
makeChemistryTabulationMethods (psiQGDReactionThermo, constFluidEThermoPhysics)
makeChemistryTabulationMethods (psiQGDReactionThermo, constAdiabaticFluidEThermoPhysics)
makeChemistryTabulationMethods (psiQGDReactionThermo, constEThermoPhysics)
makeChemistrySolverTypes (psiQGDReactionThermo, constGasEThermoPhysics)
makeChemistrySolverTypes (psiQGDReactionThermo, gasEThermoPhysics)
makeChemistrySolverTypes (psiQGDReactionThermo, constIncompressibleGasEThermoPhysics)
makeChemistrySolverTypes (psiQGDReactionThermo, incompressibleGasEThermoPhysics)
makeChemistrySolverTypes (psiQGDReactionThermo, icoPoly8EThermoPhysics)
makeChemistrySolverTypes (psiQGDReactionThermo, constFluidEThermoPhysics)
makeChemistrySolverTypes (psiQGDReactionThermo, constAdiabaticFluidEThermoPhysics)
makeChemistrySolverTypes (psiQGDReactionThermo, constEThermoPhysics)
makeCombustion (psiQGDReactionThermo)
makeCombustionTypesThermo (diffusion, psiQGDReactionThermo, gasHThermoPhysics)
makeCombustionTypesThermo (diffusion, psiQGDReactionThermo, constGasHThermoPhysics)
makeCombustionTypesThermo (diffusion, psiQGDReactionThermo, gasEThermoPhysics)
makeCombustionTypesThermo (diffusion, psiQGDReactionThermo, constGasEThermoPhysics)
makeCombustionTypesThermo (diffusionMulticomponent, psiQGDReactionThermo, gasHThermoPhysics)
makeCombustionTypesThermo (diffusionMulticomponent, psiQGDReactionThermo, constGasHThermoPhysics)
makeCombustionTypes (EDC, psiQGDReactionThermo)
makeCombustionTypesThermo (eddyDissipationDiffusionModel, psiQGDReactionThermo, gasHThermoPhysics)
makeCombustionTypesThermo (eddyDissipationDiffusionModel, psiQGDReactionThermo, constGasHThermoPhysics)
makeCombustionTypesThermo (FSD, psiQGDReactionThermo, gasHThermoPhysics)
makeCombustionTypesThermo (FSD, psiQGDReactionThermo, constGasHThermoPhysics)
makeCombustionTypesThermo (FSD, psiQGDReactionThermo, gasEThermoPhysics)
makeCombustionTypesThermo (FSD, psiQGDReactionThermo, constGasEThermoPhysics)
makeCombustionTypesThermo (infinitelyFastChemistry, psiQGDReactionThermo, gasHThermoPhysics)
makeCombustionTypesThermo (infinitelyFastChemistry, psiQGDReactionThermo, constGasHThermoPhysics)
makeCombustionTypesThermo (infinitelyFastChemistry, psiQGDReactionThermo, gasEThermoPhysics)
makeCombustionTypesThermo (infinitelyFastChemistry, psiQGDReactionThermo, constGasEThermoPhysics)
makeCombustionTypes (laminar, psiQGDReactionThermo)
makeCombustionTypes (noCombustion, psiQGDReactionThermo)
makeCombustionTypes (PaSR, psiQGDReactionThermo)
makeCombustionTypes (zoneCombustion, psiQGDReactionThermo)
makePatchTypeField (fvPatchVectorField, cosVelocityFvPatchVectorField)
makePatchTypeField (fvPatchScalarField, qgdFluxFvPatchScalarField)
makePatchTypeField (fvPatchScalarField, qhdFluxFvPatchScalarField)
template<class T >
tmp< GeometricField< T,
Foam::fvsPatchField,
Foam::surfaceMesh > > qgdInterpolate (const GeometricField< T, Foam::fvPatchField, Foam::volMesh > &psi)
template<class T >
tmp< GeometricField< T,
Foam::fvsPatchField,
Foam::surfaceMesh > > qgdInterpolate (const tmp< GeometricField< T, Foam::fvPatchField, Foam::volMesh >> &tpsi)
template<class T >
tmp< GeometricField< T,
Foam::fvsPatchField,
Foam::surfaceMesh > > qgdFlux (const GeometricField< scalar, Foam::fvsPatchField, Foam::surfaceMesh > &flux, const GeometricField< T, Foam::fvPatchField, Foam::volMesh > &psi, const GeometricField< T, Foam::fvsPatchField, Foam::surfaceMesh > &psif, const word fluxName)
template<class T >
tmp< GeometricField< T,
Foam::fvsPatchField,
Foam::surfaceMesh > > qgdFlux (const GeometricField< scalar, Foam::fvsPatchField, Foam::surfaceMesh > &flux, const GeometricField< T, Foam::fvPatchField, Foam::volMesh > &psi, const GeometricField< T, Foam::fvsPatchField, Foam::surfaceMesh > &psif)
template<class T >
tmp< GeometricField< T,
Foam::fvsPatchField,
Foam::surfaceMesh > > qgdFlux (const tmp< GeometricField< scalar, Foam::fvsPatchField, Foam::surfaceMesh >> &flux, const tmp< GeometricField< T, Foam::fvPatchField, Foam::volMesh >> &psi, const tmp< GeometricField< T, Foam::fvsPatchField, Foam::surfaceMesh >> &psif)
template<class Thermo >
powerLawTransport< Thermo > operator+ (const powerLawTransport< Thermo > &, const powerLawTransport< Thermo > &)
template<class Thermo >
powerLawTransport< Thermo > operator- (const powerLawTransport< Thermo > &, const powerLawTransport< Thermo > &)
template<class Thermo >
powerLawTransport< Thermo > operator* (const scalar, const powerLawTransport< Thermo > &)
template<class Thermo >
powerLawTransport< Thermo > operator== (const powerLawTransport< Thermo > &, const powerLawTransport< Thermo > &)
template<class Thermo >
Ostream & operator<< (Ostream &, const powerLawTransport< Thermo > &)
defineTypeNameAndDebug (psiQGDReactionThermo, 0)
defineRunTimeSelectionTable (psiQGDReactionThermo, fvMesh)
defineRunTimeSelectionTable (psiQGDReactionThermo, fvMeshDictPhase)
makeReactionThermos (psiQGDThermo, psiQGDReactionThermo, hePsiQGDThermo, homogeneousMixture, constTransport, sensibleEnthalpy, hConstThermo, perfectGas, specie)
makeReactionThermos (psiQGDThermo, psiQGDReactionThermo, hePsiQGDThermo, inhomogeneousMixture, constTransport, sensibleEnthalpy, hConstThermo, perfectGas, specie)
makeReactionThermos (psiQGDThermo, psiQGDReactionThermo, hePsiQGDThermo, veryInhomogeneousMixture, constTransport, sensibleEnthalpy, hConstThermo, perfectGas, specie)
makeReactionThermos (psiQGDThermo, psiQGDReactionThermo, hePsiQGDThermo, homogeneousMixture, sutherlandTransport, sensibleEnthalpy, hConstThermo, perfectGas, specie)
makeReactionThermos (psiQGDThermo, psiQGDReactionThermo, hePsiQGDThermo, inhomogeneousMixture, sutherlandTransport, sensibleEnthalpy, hConstThermo, perfectGas, specie)
makeReactionThermos (psiQGDThermo, psiQGDReactionThermo, hePsiQGDThermo, veryInhomogeneousMixture, sutherlandTransport, sensibleEnthalpy, hConstThermo, perfectGas, specie)
makeReactionThermos (psiQGDThermo, psiQGDReactionThermo, hePsiQGDThermo, homogeneousMixture, sutherlandTransport, sensibleEnthalpy, janafThermo, perfectGas, specie)
makeReactionThermos (psiQGDThermo, psiQGDReactionThermo, hePsiQGDThermo, inhomogeneousMixture, sutherlandTransport, sensibleEnthalpy, janafThermo, perfectGas, specie)
makeReactionThermos (psiQGDThermo, psiQGDReactionThermo, hePsiQGDThermo, veryInhomogeneousMixture, sutherlandTransport, sensibleEnthalpy, janafThermo, perfectGas, specie)
makeThermoPhysicsReactionThermos (psiQGDThermo, psiQGDReactionThermo, hePsiQGDThermo, multiComponentMixture, constGasHThermoPhysics)
makeThermoPhysicsReactionThermos (psiQGDThermo, psiQGDReactionThermo, hePsiQGDThermo, multiComponentMixture, gasHThermoPhysics)
makeThermoPhysicsReactionThermos (psiQGDThermo, psiQGDReactionThermo, hePsiQGDThermo, multiComponentMixture, constGasEThermoPhysics)
makeThermoPhysicsReactionThermos (psiQGDThermo, psiQGDReactionThermo, hePsiQGDThermo, multiComponentMixture, gasEThermoPhysics)
makeThermoPhysicsReactionThermos (psiQGDThermo, psiQGDReactionThermo, hePsiQGDThermo, reactingMixture, constGasHThermoPhysics)
makeThermoPhysicsReactionThermos (psiQGDThermo, psiQGDReactionThermo, hePsiQGDThermo, reactingMixture, gasHThermoPhysics)
makeThermoPhysicsReactionThermos (psiQGDThermo, psiQGDReactionThermo, hePsiQGDThermo, singleStepReactingMixture, gasHThermoPhysics)
makeThermoPhysicsReactionThermos (psiQGDThermo, psiQGDReactionThermo, hePsiQGDThermo, reactingMixture, constGasEThermoPhysics)
makeThermoPhysicsReactionThermos (psiQGDThermo, psiQGDReactionThermo, hePsiQGDThermo, reactingMixture, gasEThermoPhysics)
makeThermoPhysicsReactionThermos (psiQGDThermo, psiQGDReactionThermo, hePsiQGDThermo, singleStepReactingMixture, gasEThermoPhysics)
makeThermoPhysicsReactionThermo (psiQGDReactionThermo, hePsiQGDThermo, singleComponentMixture, constGasHThermoPhysics)
makeThermoPhysicsReactionThermo (psiQGDReactionThermo, hePsiQGDThermo, singleComponentMixture, gasHThermoPhysics)
makeThermoPhysicsReactionThermo (psiQGDReactionThermo, hePsiQGDThermo, singleComponentMixture, constGasEThermoPhysics)
makeThermoPhysicsReactionThermo (psiQGDReactionThermo, hePsiQGDThermo, singleComponentMixture, gasEThermoPhysics)
defineTypeNameAndDebug (psiQGDThermo, 0)
defineRunTimeSelectionTable (psiQGDThermo, fvMesh)
makeThermo (psiQGDThermo, hePsiQGDThermo, pureMixture, constTransport, sensibleInternalEnergy, hConstThermo, perfectGas, specie)
makeThermo (psiQGDThermo, hePsiQGDThermo, pureMixture, sutherlandTransport, sensibleInternalEnergy, hConstThermo, perfectGas, specie)
makeThermo (psiQGDThermo, hePsiQGDThermo, pureMixture, constTransport, sensibleInternalEnergy, eConstThermo, perfectGas, specie)
makeThermo (psiQGDThermo, hePsiQGDThermo, pureMixture, powerLawTransport, sensibleInternalEnergy, hConstThermo, perfectGas, specie)
defineTypeNameAndDebug (QGDThermo, 0)
defineTypeNameAndDebug (rhoQGDThermo, 0)
defineRunTimeSelectionTable (rhoQGDThermo, fvMesh)
makeThermo (rhoQGDThermo, heRhoQGDThermo, pureMixture, constTransport, sensibleInternalEnergy, hConstThermo, perfectGas, specie)
makeThermo (rhoQGDThermo, heRhoQGDThermo, pureMixture, sutherlandTransport, sensibleInternalEnergy, hConstThermo, perfectGas, specie)
makeThermo (rhoQGDThermo, heRhoQGDThermo, pureMixture, constTransport, sensibleInternalEnergy, eConstThermo, perfectGas, specie)
makeThermo (rhoQGDThermo, heRhoQGDThermo, pureMixture, powerLawTransport, sensibleInternalEnergy, hConstThermo, perfectGas, specie)
makeThermo (rhoQGDThermo, heRhoQGDThermo, pureMixture, constTransport, sensibleInternalEnergy, hConstThermo, rhoConst, specie)
makePatchTypeField (fvPatchScalarField, mQhdFluxFvPatchScalarField)
defineTypeNameAndDebug (twoPhaseIcoQGDThermo, 0)
template<class Type >
tmp< GeometricField< Type,
fvsPatchField, surfaceMesh > > interpolate (const GeometricField< Type, fvPatchField, volMesh > &vf, const surfaceScalarField &dir, const word &reconFieldName=word::null)
Interpolate field vf according to direction dir.
Typedef Documentation
typedef List<face> faceList
Definition at line 40 of file GaussVolPointBase3D.H.
Function Documentation
Foam::makeChemistryModel (psiQGDReactionThermo)
Foam::makeChemistryModelType (StandardChemistryModel , psiQGDReactionThermo , constGasEThermoPhysics)
Foam::makeChemistryModelType (StandardChemistryModel , psiQGDReactionThermo , gasEThermoPhysics)
Foam::makeChemistryModelType (StandardChemistryModel , psiQGDReactionThermo , constIncompressibleGasEThermoPhysics)
Foam::makeChemistryModelType (StandardChemistryModel , psiQGDReactionThermo , incompressibleGasEThermoPhysics)
Foam::makeChemistryModelType (StandardChemistryModel , psiQGDReactionThermo , icoPoly8EThermoPhysics)
Foam::makeChemistryModelType (StandardChemistryModel , psiQGDReactionThermo , constFluidEThermoPhysics)
Foam::makeChemistryModelType (StandardChemistryModel , psiQGDReactionThermo , constAdiabaticFluidEThermoPhysics)
Foam::makeChemistryModelType (StandardChemistryModel , psiQGDReactionThermo , constEThermoPhysics)
Foam::makeChemistryModelType (TDACChemistryModel , psiQGDReactionThermo , constGasEThermoPhysics)
Foam::makeChemistryModelType (TDACChemistryModel , psiQGDReactionThermo , gasEThermoPhysics)
Foam::makeChemistryModelType (TDACChemistryModel , psiQGDReactionThermo , constIncompressibleGasEThermoPhysics)
Foam::makeChemistryModelType (TDACChemistryModel , psiQGDReactionThermo , incompressibleGasEThermoPhysics)
Foam::makeChemistryModelType (TDACChemistryModel , psiQGDReactionThermo , icoPoly8EThermoPhysics)
Foam::makeChemistryModelType (TDACChemistryModel , psiQGDReactionThermo , constFluidEThermoPhysics)
Foam::makeChemistryModelType (TDACChemistryModel , psiQGDReactionThermo , constAdiabaticFluidEThermoPhysics)
Foam::makeChemistryModelType (TDACChemistryModel , psiQGDReactionThermo , constEThermoPhysics)
Foam::makeChemistryReductionMethods (psiQGDReactionThermo , constGasHThermoPhysics)
Foam::makeChemistryReductionMethods (psiQGDReactionThermo , gasHThermoPhysics)
Foam::makeChemistryReductionMethods (psiQGDReactionThermo , constIncompressibleGasHThermoPhysics)
Foam::makeChemistryReductionMethods (psiQGDReactionThermo , incompressibleGasHThermoPhysics)
Foam::makeChemistryReductionMethods (psiQGDReactionThermo , icoPoly8HThermoPhysics)
Foam::makeChemistryReductionMethods (psiQGDReactionThermo , constFluidHThermoPhysics)
Foam::makeChemistryReductionMethods (psiQGDReactionThermo , constAdiabaticFluidHThermoPhysics)
Foam::makeChemistryReductionMethods (psiQGDReactionThermo , constHThermoPhysics)
Foam::makeChemistryReductionMethods (psiQGDReactionThermo , constGasEThermoPhysics)
Foam::makeChemistryReductionMethods (psiQGDReactionThermo , gasEThermoPhysics)
Foam::makeChemistryReductionMethods (psiQGDReactionThermo , constIncompressibleGasEThermoPhysics)
Foam::makeChemistryReductionMethods (psiQGDReactionThermo , incompressibleGasEThermoPhysics)
Foam::makeChemistryReductionMethods (psiQGDReactionThermo , icoPoly8EThermoPhysics)
Foam::makeChemistryReductionMethods (psiQGDReactionThermo , constFluidEThermoPhysics)
Foam::makeChemistryReductionMethods (psiQGDReactionThermo , constAdiabaticFluidEThermoPhysics)
Foam::makeChemistryReductionMethods (psiQGDReactionThermo , constEThermoPhysics)
Foam::makeChemistryTabulationMethods (psiQGDReactionThermo , constGasHThermoPhysics)
Foam::makeChemistryTabulationMethods (psiQGDReactionThermo , gasHThermoPhysics)
Foam::makeChemistryTabulationMethods (psiQGDReactionThermo , constIncompressibleGasHThermoPhysics)
Foam::makeChemistryTabulationMethods (psiQGDReactionThermo , incompressibleGasHThermoPhysics)
Foam::makeChemistryTabulationMethods (psiQGDReactionThermo , icoPoly8HThermoPhysics)
Foam::makeChemistryTabulationMethods (psiQGDReactionThermo , constFluidHThermoPhysics)
Foam::makeChemistryTabulationMethods (psiQGDReactionThermo , constAdiabaticFluidHThermoPhysics)
Foam::makeChemistryTabulationMethods (psiQGDReactionThermo , constHThermoPhysics)
Foam::makeChemistryTabulationMethods (psiQGDReactionThermo , constGasEThermoPhysics)
Foam::makeChemistryTabulationMethods (psiQGDReactionThermo , gasEThermoPhysics)
Foam::makeChemistryTabulationMethods (psiQGDReactionThermo , constIncompressibleGasEThermoPhysics)
Foam::makeChemistryTabulationMethods (psiQGDReactionThermo , incompressibleGasEThermoPhysics)
Foam::makeChemistryTabulationMethods (psiQGDReactionThermo , icoPoly8EThermoPhysics)
Foam::makeChemistryTabulationMethods (psiQGDReactionThermo , constFluidEThermoPhysics)
Foam::makeChemistryTabulationMethods (psiQGDReactionThermo , constAdiabaticFluidEThermoPhysics)
Foam::makeChemistryTabulationMethods (psiQGDReactionThermo , constEThermoPhysics)
Foam::makeChemistrySolverTypes (psiQGDReactionThermo , constGasEThermoPhysics)
Foam::makeChemistrySolverTypes (psiQGDReactionThermo , gasEThermoPhysics)
Foam::makeChemistrySolverTypes (psiQGDReactionThermo , constIncompressibleGasEThermoPhysics)
Foam::makeChemistrySolverTypes (psiQGDReactionThermo , incompressibleGasEThermoPhysics)
Foam::makeChemistrySolverTypes (psiQGDReactionThermo , icoPoly8EThermoPhysics)
Foam::makeChemistrySolverTypes (psiQGDReactionThermo , constFluidEThermoPhysics)
Foam::makeChemistrySolverTypes (psiQGDReactionThermo , constAdiabaticFluidEThermoPhysics)
Foam::makeChemistrySolverTypes (psiQGDReactionThermo , constEThermoPhysics)
Foam::makeCombustion (psiQGDReactionThermo)
Foam::makeCombustionTypesThermo (diffusion , psiQGDReactionThermo , gasHThermoPhysics)
Foam::makeCombustionTypesThermo (diffusion , psiQGDReactionThermo , constGasHThermoPhysics)
Foam::makeCombustionTypesThermo (diffusion , psiQGDReactionThermo , gasEThermoPhysics)
Foam::makeCombustionTypesThermo (diffusion , psiQGDReactionThermo , constGasEThermoPhysics)
Foam::makeCombustionTypesThermo (diffusionMulticomponent , psiQGDReactionThermo , gasHThermoPhysics)
Foam::makeCombustionTypesThermo (diffusionMulticomponent , psiQGDReactionThermo , constGasHThermoPhysics)
Foam::makeCombustionTypes (EDC , psiQGDReactionThermo)
Foam::makeCombustionTypesThermo (eddyDissipationDiffusionModel , psiQGDReactionThermo , gasHThermoPhysics)
Foam::makeCombustionTypesThermo (eddyDissipationDiffusionModel , psiQGDReactionThermo , constGasHThermoPhysics)
Foam::makeCombustionTypesThermo (FSD , psiQGDReactionThermo , gasHThermoPhysics)
Foam::makeCombustionTypesThermo (FSD , psiQGDReactionThermo , constGasHThermoPhysics)
Foam::makeCombustionTypesThermo (FSD , psiQGDReactionThermo , gasEThermoPhysics)
Foam::makeCombustionTypesThermo (FSD , psiQGDReactionThermo , constGasEThermoPhysics)
Foam::makeCombustionTypesThermo (infinitelyFastChemistry , psiQGDReactionThermo , gasHThermoPhysics)
Foam::makeCombustionTypesThermo (infinitelyFastChemistry , psiQGDReactionThermo , constGasHThermoPhysics)
Foam::makeCombustionTypesThermo (infinitelyFastChemistry , psiQGDReactionThermo , gasEThermoPhysics)
Foam::makeCombustionTypesThermo (infinitelyFastChemistry , psiQGDReactionThermo , constGasEThermoPhysics)
Foam::makeCombustionTypes (laminar , psiQGDReactionThermo)
Foam::makeCombustionTypes (noCombustion , psiQGDReactionThermo)
Foam::makeCombustionTypes (PaSR , psiQGDReactionThermo)
Foam::makeCombustionTypes (zoneCombustion , psiQGDReactionThermo)
Foam::makePatchTypeField (fvPatchVectorField , cosVelocityFvPatchVectorField)
Foam::makePatchTypeField (fvPatchScalarField , qgdFluxFvPatchScalarField)
Foam::makePatchTypeField (fvPatchScalarField , qhdFluxFvPatchScalarField)
tmp<GeometricField<T, Foam::fvsPatchField, Foam::surfaceMesh> > Foam::qgdInterpolate (const GeometricField< T, Foam::fvPatchField, Foam::volMesh > & psi)
Definition at line 36 of file QGDInterpolate.H.
References interpolate(), and psi.
Referenced by forAll().
tmp<GeometricField<T, Foam::fvsPatchField, Foam::surfaceMesh> > Foam::qgdInterpolate (const tmp< GeometricField< T, Foam::fvPatchField, Foam::volMesh >> & tpsi)
Definition at line 67 of file QGDInterpolate.H.
tmp<GeometricField<T, Foam::fvsPatchField, Foam::surfaceMesh> > Foam::qgdFlux (const GeometricField< scalar, Foam::fvsPatchField, Foam::surfaceMesh > & flux, const GeometricField< T, Foam::fvPatchField, Foam::volMesh > & psi, const GeometricField< T, Foam::fvsPatchField, Foam::surfaceMesh > & psif, const word fluxName)
Definition at line 75 of file QGDInterpolate.H.
Referenced by forAll(), if(), and qgdFlux().
tmp<GeometricField<T, Foam::fvsPatchField, Foam::surfaceMesh> > Foam::qgdFlux (const GeometricField< scalar, Foam::fvsPatchField, Foam::surfaceMesh > & flux, const GeometricField< T, Foam::fvPatchField, Foam::volMesh > & psi, const GeometricField< T, Foam::fvsPatchField, Foam::surfaceMesh > & psif)
Definition at line 106 of file QGDInterpolate.H.
References qgdFlux().
tmp<GeometricField<T, Foam::fvsPatchField, Foam::surfaceMesh> > Foam::qgdFlux (const tmp< GeometricField< scalar, Foam::fvsPatchField, Foam::surfaceMesh >> & flux, const tmp< GeometricField< T, Foam::fvPatchField, Foam::volMesh >> & psi, const tmp< GeometricField< T, Foam::fvsPatchField, Foam::surfaceMesh >> & psif)
Definition at line 120 of file QGDInterpolate.H.
References psi, and qgdFlux().
powerLawTransport<Thermo> Foam::operator+ (const powerLawTransport< Thermo > & , const powerLawTransport< Thermo > &) inline
powerLawTransport<Thermo> Foam::operator- (const powerLawTransport< Thermo > & , const powerLawTransport< Thermo > &) inline
powerLawTransport<Thermo> Foam::operator* (const scalar , const powerLawTransport< Thermo > &) inline
powerLawTransport<Thermo> Foam::operator== (const powerLawTransport< Thermo > & , const powerLawTransport< Thermo > &) inline
Ostream& Foam::operator<< (Ostream & , const powerLawTransport< Thermo > &)
Foam::defineTypeNameAndDebug (psiQGDReactionThermo , 0)
Referenced by QGDThermo::QGDThermo(), and twoPhaseIcoQGDThermo::twoPhaseIcoQGDThermo().
Foam::defineRunTimeSelectionTable (psiQGDReactionThermo , fvMesh)
Foam::defineRunTimeSelectionTable (psiQGDReactionThermo , fvMeshDictPhase)
Foam::makeReactionThermos (psiQGDThermo , psiQGDReactionThermo , hePsiQGDThermo , homogeneousMixture , constTransport , sensibleEnthalpy , hConstThermo , perfectGas , specie)
Foam::makeReactionThermos (psiQGDThermo , psiQGDReactionThermo , hePsiQGDThermo , inhomogeneousMixture , constTransport , sensibleEnthalpy , hConstThermo , perfectGas , specie)
Foam::makeReactionThermos (psiQGDThermo , psiQGDReactionThermo , hePsiQGDThermo , veryInhomogeneousMixture , constTransport , sensibleEnthalpy , hConstThermo , perfectGas , specie)
Foam::makeReactionThermos (psiQGDThermo , psiQGDReactionThermo , hePsiQGDThermo , homogeneousMixture , sutherlandTransport , sensibleEnthalpy , hConstThermo , perfectGas , specie)
Foam::makeReactionThermos (psiQGDThermo , psiQGDReactionThermo , hePsiQGDThermo , inhomogeneousMixture , sutherlandTransport , sensibleEnthalpy , hConstThermo , perfectGas , specie)
Foam::makeReactionThermos (psiQGDThermo , psiQGDReactionThermo , hePsiQGDThermo , veryInhomogeneousMixture , sutherlandTransport , sensibleEnthalpy , hConstThermo , perfectGas , specie)
Foam::makeReactionThermos (psiQGDThermo , psiQGDReactionThermo , hePsiQGDThermo , homogeneousMixture , sutherlandTransport , sensibleEnthalpy , janafThermo , perfectGas , specie)
Foam::makeReactionThermos (psiQGDThermo , psiQGDReactionThermo , hePsiQGDThermo , inhomogeneousMixture , sutherlandTransport , sensibleEnthalpy , janafThermo , perfectGas , specie)
Foam::makeReactionThermos (psiQGDThermo , psiQGDReactionThermo , hePsiQGDThermo , veryInhomogeneousMixture , sutherlandTransport , sensibleEnthalpy , janafThermo , perfectGas , specie)
Foam::makeThermoPhysicsReactionThermos (psiQGDThermo , psiQGDReactionThermo , hePsiQGDThermo , multiComponentMixture , constGasHThermoPhysics)
Foam::makeThermoPhysicsReactionThermos (psiQGDThermo , psiQGDReactionThermo , hePsiQGDThermo , multiComponentMixture , gasHThermoPhysics)
Foam::makeThermoPhysicsReactionThermos (psiQGDThermo , psiQGDReactionThermo , hePsiQGDThermo , multiComponentMixture , constGasEThermoPhysics)
Foam::makeThermoPhysicsReactionThermos (psiQGDThermo , psiQGDReactionThermo , hePsiQGDThermo , multiComponentMixture , gasEThermoPhysics)
Foam::makeThermoPhysicsReactionThermos (psiQGDThermo , psiQGDReactionThermo , hePsiQGDThermo , reactingMixture , constGasHThermoPhysics)
Foam::makeThermoPhysicsReactionThermos (psiQGDThermo , psiQGDReactionThermo , hePsiQGDThermo , reactingMixture , gasHThermoPhysics)
Foam::makeThermoPhysicsReactionThermos (psiQGDThermo , psiQGDReactionThermo , hePsiQGDThermo , singleStepReactingMixture , gasHThermoPhysics)
Foam::makeThermoPhysicsReactionThermos (psiQGDThermo , psiQGDReactionThermo , hePsiQGDThermo , reactingMixture , constGasEThermoPhysics)
Foam::makeThermoPhysicsReactionThermos (psiQGDThermo , psiQGDReactionThermo , hePsiQGDThermo , reactingMixture , gasEThermoPhysics)
Foam::makeThermoPhysicsReactionThermos (psiQGDThermo , psiQGDReactionThermo , hePsiQGDThermo , singleStepReactingMixture , gasEThermoPhysics)
Foam::makeThermoPhysicsReactionThermo (psiQGDReactionThermo , hePsiQGDThermo , singleComponentMixture , constGasHThermoPhysics)
Foam::makeThermoPhysicsReactionThermo (psiQGDReactionThermo , hePsiQGDThermo , singleComponentMixture , gasHThermoPhysics)
Foam::makeThermoPhysicsReactionThermo (psiQGDReactionThermo , hePsiQGDThermo , singleComponentMixture , constGasEThermoPhysics)
Foam::makeThermoPhysicsReactionThermo (psiQGDReactionThermo , hePsiQGDThermo , singleComponentMixture , gasEThermoPhysics)
Foam::defineTypeNameAndDebug (psiQGDThermo , 0)
Foam::defineRunTimeSelectionTable (psiQGDThermo , fvMesh)
Foam::makeThermo (psiQGDThermo , hePsiQGDThermo , pureMixture , constTransport , sensibleInternalEnergy , hConstThermo , perfectGas , specie)
Foam::makeThermo (psiQGDThermo , hePsiQGDThermo , pureMixture , sutherlandTransport , sensibleInternalEnergy , hConstThermo , perfectGas , specie)
Foam::makeThermo (psiQGDThermo , hePsiQGDThermo , pureMixture , constTransport , sensibleInternalEnergy , eConstThermo , perfectGas , specie)
Foam::makeThermo (psiQGDThermo , hePsiQGDThermo , pureMixture , powerLawTransport , sensibleInternalEnergy , hConstThermo , perfectGas , specie)
Foam::defineTypeNameAndDebug (QGDThermo , 0)
Foam::defineTypeNameAndDebug (rhoQGDThermo , 0)
Foam::defineRunTimeSelectionTable (rhoQGDThermo , fvMesh)
Foam::makeThermo (rhoQGDThermo , heRhoQGDThermo , pureMixture , constTransport , sensibleInternalEnergy , hConstThermo , perfectGas , specie)
Foam::makeThermo (rhoQGDThermo , heRhoQGDThermo , pureMixture , sutherlandTransport , sensibleInternalEnergy , hConstThermo , perfectGas , specie)
Foam::makeThermo (rhoQGDThermo , heRhoQGDThermo , pureMixture , constTransport , sensibleInternalEnergy , eConstThermo , perfectGas , specie)
Foam::makeThermo (rhoQGDThermo , heRhoQGDThermo , pureMixture , powerLawTransport , sensibleInternalEnergy , hConstThermo , perfectGas , specie)
Foam::makeThermo (rhoQGDThermo , heRhoQGDThermo , pureMixture , constTransport , sensibleInternalEnergy , hConstThermo , rhoConst , specie)
Foam::makePatchTypeField (fvPatchScalarField , mQhdFluxFvPatchScalarField)
Foam::defineTypeNameAndDebug (twoPhaseIcoQGDThermo , 0)
tmp<GeometricField<Type, fvsPatchField, surfaceMesh> > Foam::interpolate (const GeometricField< Type, fvPatchField, volMesh > & vf, const surfaceScalarField & dir, const word & reconFieldName = word::null)
Interpolate field vf according to direction dir.
Definition at line 9 of file directionInterpolate.H.
Referenced by qInterfaceProperties::nearInterface(), and qgdInterpolate().