QGDsolver: particlesQGDFoam/particlesQGDFoam.C File Reference
particlesQGDFoam.C File Reference
Solver for unsteady 3D turbulent flow of perfect gas governed by quasi-gas dynamic (QGD) equations at all Mach numbers (from 0 to infinity) coupled with particles motion.
Macros
#define NO_CONTROL
Functions
int main (int argc, char *argv[])
Detailed Description
Solver for unsteady 3D turbulent flow of perfect gas governed by quasi-gas dynamic (QGD) equations at all Mach numbers (from 0 to infinity) coupled with particles motion.
Original source file particlesQGDFoam.C
QGD system of equations has been developed by scientific group from Keldysh Institute of Applied Mathematics, see http://elizarova.imamod.ru/selection-of-papers.html
Developed by UniCFD group (www.unicfd.ru) of ISP RAS (www.ispras.ru).
Definition in file particlesQGDFoam.C.
Macro Definition Documentation
#define NO_CONTROL
Function Documentation
int main (int argc, char * argv[])
——–Start———
——–End———
——–Start———
——–End———
——–Start———
——–End———
——–Start———
——–End——— # 55 "/home/jenkins/workspace/experQGDsolver-8doxigen/QGDsolver/particlesQGDFoam/particlesQGDFoam.C" 2 #include "createTimeControls.H" #include "createFvOptions.H"
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
Courant numbers used to adjust the time-step scalar CoNum = 0.0; scalar meanCoNum = 0.0;
Info<< "\nStarting time loop\n" << endl;
while (runTime.run()) { /*
Update QGD viscosity
——–Start———
——–End———
——–Start———
——–End———
——–Start———
——–End———
——–Start———
——–End——— # 88 "/home/jenkins/workspace/experQGDsolver-8doxigen/QGDsolver/particlesQGDFoam/particlesQGDFoam.C" 2
/*
Update time step
– Solve energy
Definition at line 45 of file particlesQGDFoam.C.
References e, p, psi, rho(), rhoE(), rhoESu(), rhoU(), rhoUSu(), thermo, turbulence, and U().