QGDsolver: QGD/QGDcommon/QGDEEqn.H File Reference
QGDEEqn.H File Reference
Equation of energy for QGD solver.
Functions
fvScalarMatrix EEqn (fvm::ddt(rhoE)+fvc::div(phiJmH)+fvc::div(phiQ)-fvc::div(phiPiU)-fvc::div(phiSigmaDotU))
EEqn solve ()
e correctBoundaryConditions ()
if (implicitDiffusion)
rhoE boundaryFieldRef ()
Variables
e = rhoE/rho - 0.5*magSqr(U)
else
Detailed Description
Equation of energy for QGD solver.
Original source file QGDEEqn.H
Source files
QGDEEqn.H
QGDFoam.C
Definition in file QGDEEqn.H.
Function Documentation
fvScalarMatrix EEqn (fvm:: ddtrhoE)+fvc::div(phiJmH)+fvc::div(phiQ)-fvc::div(phiPiU)-fvc::div(phiSigmaDotU)
EEqn solve ()
Referenced by if().
e correctBoundaryConditions ()
Referenced by GaussVolPoint::Div(), and GaussVolPoint::Grad().
if (implicitDiffusion)
Definition at line 49 of file QGDEEqn.H.
rhoE boundaryFieldRef ()
Variable Documentation
e = rhoE/rho - 0.5*magSqr(U)
Definition at line 45 of file QGDEEqn.H.
else
Initial value:
{
        solve
        (
            fvm::ddt(rho,e) - fvc::ddt(rhoE)
            ==
            rhoESu
        )
Definition at line 62 of file QGDEEqn.H.