QGDsolver: reactingLagrangianQGDFoam/createFields.H File Reference
createFields.H File Reference
Functions
volVectorField U (IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh)
surfaceScalarField phi ("phi", linearInterpolate(dimensionedScalar("0", dimensionSet(1,-3, 0, 0, 0), 0.0)*U)&mesh.Sf())
Info<< "Reading thermophysical
properties\n"<< endl;autoPtr
< psiQGDReactionThermo > pThermo (psiQGDReactionThermo::New(mesh))
thermo correct ()
SLGThermo slgThermo (mesh, thermo)
const word inertSpecie (thermo.get< word >("inertSpecie"))
if (!composition.species().found(inertSpecie))
const label inertIndex (composition.species()[inertSpecie])
Info<< "Creating density field"
<< endl;volScalarField rho(IOobject("rho",
runTime.timeName(), mesh,
IOobject::NO_READ,
IOobject::AUTO_WRITE),
thermo.rho());volVectorField
rhoU(IOobject("rhoU",
runTime.timeName(), mesh,
IOobject::NO_READ,
IOobject::NO_WRITE), rho *U);volScalarField
rhoE(IOobject("rhoE",
runTime.timeName(), mesh,
IOobject::NO_READ,
IOobject::NO_WRITE), rho *e+rho
*0.5 *magSqr(U));volScalarField
H(IOobject("Ht",
runTime.timeName(), mesh,
IOobject::NO_READ,
IOobject::NO_WRITE),(rhoE+p)/rho);Switch
implicitDiffusion(thermo.implicitDiffusion());Info
<< "Creating turbulence
model\n"<< endl;turbulence.reset(compressible::turbulenceModel::New(rho,
U, phi, thermo).ptr());#125"/home/jenkins/workspace/experQGDsolver-8doxigen/QGDsolver/reactingLagrangianQGDFoam/createFields.H"2Info<< "Creating combustion model\n"<< endl;autoPtr< CombustionModel< psiQGDReactionThermo > > combustion (CombustionModel< psiQGDReactionThermo >::New(thermo, turbulence()))
volScalarField Qdot (IOobject("Qdot", runTime.timeName(), mesh, IOobject::READ_IF_PRESENT, IOobject::AUTO_WRITE), mesh,)
Variables
psiQGDReactionThermo & thermo = pThermo()
basicSpecieMixture & composition = thermo.composition()
PtrList< volScalarField > & Y = composition.Y()
volScalarField & e = thermo.he()
volScalarField & p = thermo.p()
const volScalarField & T = thermo.T()
const surfaceScalarField & tauQGDf = thermo.tauQGDf()
const surfaceScalarField & hQGDf = thermo.hQGDf()
const volScalarField & gamma = thermo.gamma()
const volScalarField & psi = thermo.psi()
autoPtr
< compressible::turbulenceModel > turbulence
Function Documentation
volVectorField U (IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE) , mesh)
surfaceScalarField phi ("phi" , linearInterpolate(dimensionedScalar("0", dimensionSet(1,-3, 0, 0, 0), 0.0)*U)&mesh.Sf())
Info<< "Reading thermophysical properties\n" << endl;autoPtr<psiQGDReactionThermo> pThermo (psiQGDReactionThermo:: Newmesh)
thermo correct ()
SLGThermo slgThermo (mesh , thermo)
const word inertSpecie (thermo.get< word > "inertSpecie")
Referenced by if().
if (!composition. species).found(inertSpecie)
Definition at line 32 of file createFields.H.
References inertSpecie(), and thermo.
const label inertIndex (composition. species()[inertSpecie])
Referenced by forAll().
Info<< "Creating density field" << endl;volScalarField rho(IOobject ("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), thermo.rho());volVectorField rhoU(IOobject ("rhoU", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), rho*U);volScalarField rhoE(IOobject ("rhoE", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), rho*e + rho*0.5*magSqr(U));volScalarField H(IOobject ("Ht", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), (rhoE + p)/rho);Switch implicitDiffusion (thermo.implicitDiffusion());Info<< "Creating turbulence model\n" << endl;turbulence.reset(compressible::turbulenceModel::New (rho, U, phi, thermo).ptr());# 125 "/home/jenkins/workspace/experQGDsolver-8doxigen/QGDsolver/reactingLagrangianQGDFoam/createFields.H" 2Info<< "Creating combustion model\n" << endl;autoPtr<CombustionModel<psiQGDReactionThermo> > combustion (CombustionModel< psiQGDReactionThermo >:: Newthermo, turbulence())
volScalarField Qdot (IOobject("Qdot", runTime.timeName(), mesh, IOobject::READ_IF_PRESENT, IOobject::AUTO_WRITE) , mesh)
Variable Documentation
psiQGDReactionThermo& thermo = pThermo()
Definition at line 23 of file createFields.H.
basicSpecieMixture& composition = thermo.composition()
Definition at line 28 of file createFields.H.
Referenced by forAll().
PtrList<volScalarField>& Y = composition.Y()
Definition at line 29 of file createFields.H.
Referenced by forAll(), and main().
volScalarField& e = thermo.he()
Definition at line 43 of file createFields.H.
volScalarField& p = thermo.p()
Definition at line 44 of file createFields.H.
const volScalarField& T = thermo.T()
Definition at line 45 of file createFields.H.
const surfaceScalarField& tauQGDf = thermo.tauQGDf()
Definition at line 47 of file createFields.H.
const surfaceScalarField& hQGDf = thermo.hQGDf()
Definition at line 48 of file createFields.H.
const volScalarField& gamma = thermo.gamma()
Definition at line 49 of file createFields.H.
const volScalarField& psi = thermo.psi()
Definition at line 50 of file createFields.H.
autoPtr<compressible::turbulenceModel> turbulence
Definition at line 52 of file createFields.H.