#!/usr/bin/bash

function check_compilation() {
    local rc=$?
    local solver=$1
    if [ "$rc" = '0' ]; then
        echo "$solver was compiled"
    else
        echo "$solver was compiled with errors"
        exit -1
    fi
}

cd QGDFoam; ./Allwmake
check_compilation QGDFoam
cd ../

cd rhoQGDFoam; ./Allwmake
rc=$?
check_compilation rhoQGDFoam
cd ../

cd QHDFoam; ./Allwmake
check_compilation QHDFoam
cd ../

cd mulesQHDFoam; ./Allwmake
rc=$?
check_compilation mulesQHDFoam
cd ../

cd zQGDFoam; ./Allwmake
check_compilation zQGDFoam
cd ../

cd interQHDFoam; ./Allwmake
check_compilation interQHFoam
cd ../

cd particlesQGDFoam; ./Allwmake
check_compilation particlesQGFoam
cd ../

cd particlesQHDFoam; ./Allwmake
check_compilation particlesQHDFoam
cd ../

cd QHDDyMFoam; ./Allwmake
check_compilation QHDDyMFoam
cd ../

cd SRFQHDFoam; ./Allwmake
check_compilation SRFQHDFoam
cd ../

cd reactingLagrangianQGDFoam; ./Allwmake
check_compilation reactingLagrangianQGDFoam
cd ../

cd rhoReactingLagrangianQGDFoam; ./Allwmake
check_compilation rhoReactingLagrangianQGDFoam
cd ../

cd scalarTransportQHDFoam; ./Allwmake
check_compilation scalarTransportQHDFoam
cd ../

cd utils/selectBadCells; wmake
check_compilation selectBadCells
cd ../../

exit 0

#
#END-OF-FILE
#

