#!/bin/sh

cd QGDFoam; ./Allwclean; cd ../

cd rhoQGDFoam; ./Allwclean; cd ../

cd QHDFoam; ./Allwclean; cd ../

cd mulesQHDFoam; ./Allwclean; cd ../

cd zQGDFoam; ./Allwclean; cd ../

cd interQHDFoam; ./Allwclean; cd ../

cd particlesQGDFoam; ./Allwclean; cd ../

cd particlesQHDFoam; ./Allwclean; cd ../

cd QHDDyMFoam; ./Allwclean; cd ../

cd SRFQHDFoam; ./Allwclean; cd ../

cd reactingLagrangianQGDFoam; ./Allwclean; cd ../

cd reactingQGDFoam; ./Allwclean; cd ../

cd scalarTransportQHDFoam; ./Allwclean; cd ../

cd utils/selectBadCells; wclean; cd ../../

exit 0

#
#END-OF-FILE
#

