QGDsolver: reactingLagrangianQGDFoam/addEnergyFluxes.H File Reference
addEnergyFluxes.H File Reference
Functions
surfaceScalarField Hif ("Hif", Hf *0.0)
volScalarField Ei (IOobject("Ei", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), mesh, dimEnergy/dimMass)
surfaceScalarField Eif ("Eif", Hf *0.0)
forAll (Y, iCmpt)
Function Documentation
surfaceScalarField Hif ("Hif" , Hf *0. 0)
volScalarField Ei (IOobject("Ei", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE) , mesh , dimEnergy/ dimMass)
Referenced by forAll().
surfaceScalarField Eif ("Eif" , Hf *0. 0)
Referenced by forAll().
forAll (Y , iCmpt)
Definition at line 42 of file addEnergyFluxes.H.
References alphauf, diffusiveFlux(), Ei(), Eif(), forAll(), Hif, p, phiQ, Foam::qgdFlux(), Foam::qgdInterpolate(), T, thermo, turbulence, and Y.