QGDsolver: QGDsolver: qInterfaceProperties Class Reference
qInterfaceProperties Class Reference
Public Member Functions
qInterfaceProperties (const volScalarField &alpha1, const volVectorField &U, const IOdictionary &)
scalar cAlpha () const
const dimensionedScalar & deltaN () const
const surfaceScalarField & nHatf () const
tmp< volScalarField > sigmaK () const
tmp< surfaceScalarField > surfaceTensionForce () const
tmp< volScalarField > nearInterface () const
void correct ()
bool read ()
Detailed Description
Definition at line 58 of file qInterfaceProperties.H.
Constructor & Destructor Documentation
qInterfaceProperties (const volScalarField & alpha1, const volVectorField & U, const IOdictionary & dict)
Definition at line 158 of file qInterfaceProperties.C.
Member Function Documentation
scalar cAlpha () const [inline]
Definition at line 116 of file qInterfaceProperties.H.
const dimensionedScalar& deltaN () const [inline]
Definition at line 121 of file qInterfaceProperties.H.
const surfaceScalarField& nHatf () const [inline]
Definition at line 126 of file qInterfaceProperties.H.
Foam::tmp< Foam::volScalarField > sigmaK () const
Definition at line 212 of file qInterfaceProperties.C.
Referenced by qInterfaceProperties::surfaceTensionForce().
Foam::tmp< Foam::surfaceScalarField > surfaceTensionForce () const
Definition at line 219 of file qInterfaceProperties.C.
References Foam::interpolate(), and qInterfaceProperties::sigmaK().
Foam::tmp< Foam::volScalarField > nearInterface () const
Definition at line 226 of file qInterfaceProperties.C.
void correct ()
Reimplemented in twoPhaseIcoQGDThermo.
Definition at line 232 of file qInterfaceProperties.C.
bool read ()
Reimplemented in twoPhaseIcoQGDThermo.
Definition at line 238 of file qInterfaceProperties.C.
The documentation for this class was generated from the following files:
TwoPhaseQGD/thermoModels/qInterfaceProperties/qInterfaceProperties.H
TwoPhaseQGD/thermoModels/qInterfaceProperties/qInterfaceProperties.C
$mathjax