QGDsolver: QGDsolver: rhoQGDThermo Class Reference
rhoQGDThermo Class Reference
Public Member Functions
TypeName ("rhoQGDThermo")
declareRunTimeSelectionTable (autoPtr, rhoQGDThermo, fvMesh,(const fvMesh &mesh, const word &phaseName),(mesh, phaseName))
rhoQGDThermo (const fvMesh &, const word &phaseName)
rhoQGDThermo (const fvMesh &, const word &phaseName, const word &dictName)
virtual ~rhoQGDThermo ()
bool read ()
const volScalarField & c () const
virtual const volScalarField & p () const
volScalarField & p ()
virtual tmp< volScalarField > rho () const
virtual tmp< volScalarField > mu () const
Static Public Member Functions
static autoPtr< rhoQGDThermo > New (const fvMesh &mesh, const word &phaseName=word::null)
static autoPtr< rhoQGDThermo > New (const fvMesh &mesh, const word &phaseName, const word &dictName)
Protected Member Functions
rhoQGDThermo (const rhoQGDThermo &)
Protected Attributes
volScalarField c_
volScalarField gamma_
Detailed Description
Definition at line 55 of file rhoQGDThermo.H.
Constructor & Destructor Documentation
rhoQGDThermo (const rhoQGDThermo &) [protected]
rhoQGDThermo (const fvMesh & mesh, const word & phaseName)
Definition at line 42 of file rhoQGDThermo.C.
References rhoQGDThermo::read().
rhoQGDThermo (const fvMesh & mesh, const word & phaseName, const word & dictName)
Definition at line 60 of file rhoQGDThermo.C.
References rhoQGDThermo::read().
~rhoQGDThermo () [virtual]
Definition at line 102 of file rhoQGDThermo.C.
Member Function Documentation
TypeName ("rhoQGDThermo")
Reimplemented from QGDThermo.
declareRunTimeSelectionTable (autoPtr , rhoQGDThermo , fvMesh , (const fvMesh &mesh, const word &phaseName) , (mesh, phaseName))
Foam::autoPtr< Foam::rhoQGDThermo > New (const fvMesh & mesh, const word & phaseName = word::null) [static]
Definition at line 82 of file rhoQGDThermo.C.
Foam::autoPtr< Foam::rhoQGDThermo > New (const fvMesh & mesh, const word & phaseName, const word & dictName) [static]
Definition at line 91 of file rhoQGDThermo.C.
bool read () [virtual]
Reimplemented from QGDThermo.
Definition at line 110 of file rhoQGDThermo.C.
References QGDThermo::read().
Referenced by rhoQGDThermo::rhoQGDThermo().
const Foam::volScalarField & c () const [virtual]
Implements QGDThermo.
Definition at line 125 of file rhoQGDThermo.C.
References rhoQGDThermo::c_.
const Foam::volScalarField & p () const [virtual]
Implements QGDThermo.
Definition at line 130 of file rhoQGDThermo.C.
Referenced by rhoQGDThermo::p().
Foam::volScalarField & p ()
Definition at line 135 of file rhoQGDThermo.C.
References rhoQGDThermo::p().
Foam::tmp< Foam::volScalarField > rho () const [virtual]
Implements QGDThermo.
Definition at line 140 of file rhoQGDThermo.C.
Foam::tmp< Foam::volScalarField > mu () const [virtual]
Implements QGDThermo.
Definition at line 145 of file rhoQGDThermo.C.
Member Data Documentation
volScalarField c_ [protected]
Definition at line 68 of file rhoQGDThermo.H.
Referenced by rhoQGDThermo::c().
volScalarField gamma_ [protected]
Definition at line 71 of file rhoQGDThermo.H.
The documentation for this class was generated from the following files:
QGD/thermoModels/rhoQGDThermo/rhoQGDThermo.H
QGD/thermoModels/rhoQGDThermo/rhoQGDThermo.C
$mathjax