QGDsolver: QGDsolver: GaussVolPointBase3D Class Reference
GaussVolPointBase3D Class Reference
Public Member Functions
GaussVolPointBase3D (const fvMesh &mesh)
~GaussVolPointBase3D ()
void faceGrad (const volScalarField &f, surfaceVectorField &gradf)
void faceGrad (const volVectorField &f, surfaceTensorField &gradf)
void faceDiv (const volVectorField &f, surfaceScalarField &divf)
void faceDiv (const volTensorField &f, surfaceVectorField &divf)
Protected Member Functions
void calcGradfIF (const volScalarField &sf, const pointScalarField &pf, const faceList &faces, surfaceVectorField &gradf, const surfaceVectorField &dfdn)
void calcGradfBF (const volScalarField &sf, const pointScalarField &pf, const faceList &faces, surfaceVectorField &gradf, const surfaceVectorField &dfdn)
void calcGradfIF (const volVectorField &sf, const pointVectorField &pf, const faceList &faces, surfaceTensorField &gradf, const surfaceTensorField &dfdn)
void calcGradfBF (const volVectorField &sf, const pointVectorField &pf, const faceList &faces, surfaceTensorField &gradf, const surfaceTensorField &dfdn)
void calcDivfIF (const volVectorField &sf, const pointVectorField &pf, const faceList &faces, surfaceScalarField &divf, const surfaceScalarField &dfdn)
void calcDivfBF (const volVectorField &sf, const pointVectorField &pf, const faceList &faces, surfaceScalarField &divf, const surfaceScalarField &dfdn)
void calcDivfIF (const volTensorField &tf, const pointTensorField &pf, const faceList &faces, surfaceVectorField &divf, const surfaceVectorField &dfdn)
void calcDivfBF (const volTensorField &sf, const pointTensorField &pf, const faceList &faces, surfaceVectorField &divf, const surfaceVectorField &dfdn)
void triCalcWeights (const fvMesh &m)
void quaCalcWeights (const fvMesh &m)
Detailed Description
Definition at line 27 of file GaussVolPointBase3D.H.
Constructor & Destructor Documentation
GaussVolPointBase3D (const fvMesh & mesh)
Definition at line 11 of file GaussVolPointBase3D.C.
References forAll(), GaussVolPointBase3D::quaCalcWeights(), and GaussVolPointBase3D::triCalcWeights().
~GaussVolPointBase3D ()
Definition at line 448 of file GaussVolPointBase3D.C.
Member Function Documentation
void calcGradfIF (const volScalarField & sf, const pointScalarField & pf, const faceList & faces, surfaceVectorField & gradf, const surfaceVectorField & dfdn) [protected]
Definition at line 711 of file GaussVolPointBase3D.C.
References dfdxif, forAll(), SCA_CMPT, and VEC_CMPT.
Referenced by GaussVolPointBase3D::faceGrad().
void calcGradfBF (const volScalarField & sf, const pointScalarField & pf, const faceList & faces, surfaceVectorField & gradf, const surfaceVectorField & dfdn) [protected]
Definition at line 742 of file GaussVolPointBase3D.C.
References dfdxbf, forAll(), SCA_CMPT, and VEC_CMPT.
Referenced by GaussVolPointBase3D::faceGrad().
void calcGradfIF (const volVectorField & sf, const pointVectorField & pf, const faceList & faces, surfaceTensorField & gradf, const surfaceTensorField & dfdn) [protected]
Definition at line 792 of file GaussVolPointBase3D.C.
References dfdxif, forAll(), and VEC_CMPT.
void calcGradfBF (const volVectorField & sf, const pointVectorField & pf, const faceList & faces, surfaceTensorField & gradf, const surfaceTensorField & dfdn) [protected]
Definition at line 839 of file GaussVolPointBase3D.C.
References dfdxbf, forAll(), and VEC_CMPT.
void calcDivfIF (const volVectorField & sf, const pointVectorField & pf, const faceList & faces, surfaceScalarField & divf, const surfaceScalarField & dfdn) [protected]
Definition at line 514 of file GaussVolPointBase3D.C.
References dfdxif, forAll(), SCA_CMPT, and VEC_CMPT.
Referenced by GaussVolPointBase3D::faceDiv().
void calcDivfBF (const volVectorField & sf, const pointVectorField & pf, const faceList & faces, surfaceScalarField & divf, const surfaceScalarField & dfdn) [protected]
Definition at line 545 of file GaussVolPointBase3D.C.
References dfdxbf, forAll(), SCA_CMPT, and VEC_CMPT.
Referenced by GaussVolPointBase3D::faceDiv().
void calcDivfIF (const volTensorField & tf, const pointTensorField & pf, const faceList & faces, surfaceVectorField & divf, const surfaceVectorField & dfdn) [protected]
Definition at line 595 of file GaussVolPointBase3D.C.
References dfdxif, forAll(), and VEC_CMPT.
void calcDivfBF (const volTensorField & sf, const pointTensorField & pf, const faceList & faces, surfaceVectorField & divf, const surfaceVectorField & dfdn) [protected]
Definition at line 645 of file GaussVolPointBase3D.C.
References dfdxbf, forAll(), and VEC_CMPT.
void triCalcWeights (const fvMesh & m) [protected]
Definition at line 131 of file GaussVolPointBase3D.C.
References forAll().
Referenced by GaussVolPointBase3D::GaussVolPointBase3D().
void quaCalcWeights (const fvMesh & m) [protected]
Definition at line 290 of file GaussVolPointBase3D.C.
References forAll().
Referenced by GaussVolPointBase3D::GaussVolPointBase3D().
void faceGrad (const volScalarField & f, surfaceVectorField & gradf)
Reimplemented in GaussVolPointBase.
Definition at line 904 of file GaussVolPointBase3D.C.
References GaussVolPointBase3D::calcGradfBF(), and GaussVolPointBase3D::calcGradfIF().
void faceGrad (const volVectorField & f, surfaceTensorField & gradf)
Reimplemented in GaussVolPointBase.
Definition at line 935 of file GaussVolPointBase3D.C.
References GaussVolPointBase3D::calcGradfBF(), and GaussVolPointBase3D::calcGradfIF().
void faceDiv (const volVectorField & f, surfaceScalarField & divf)
Reimplemented in GaussVolPointBase.
Definition at line 966 of file GaussVolPointBase3D.C.
References GaussVolPointBase3D::calcDivfBF(), and GaussVolPointBase3D::calcDivfIF().
void faceDiv (const volTensorField & f, surfaceVectorField & divf)
Reimplemented in GaussVolPointBase.
Definition at line 992 of file GaussVolPointBase3D.C.
References GaussVolPointBase3D::calcDivfBF(), and GaussVolPointBase3D::calcDivfIF().
The documentation for this class was generated from the following files:
QGD/fvsc/GaussVolPoint/GaussVolPointBase3D.H
QGD/fvsc/GaussVolPoint/GaussVolPointBase3D.C
$mathjax