QGDsolver: QGDsolver: cosVelocityFvPatchVectorField Class Reference
cosVelocityFvPatchVectorField Class Reference
Public Member Functions
TypeName ("cosVelocity")
cosVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
cosVelocityFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
cosVelocityFvPatchVectorField (const cosVelocityFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
cosVelocityFvPatchVectorField (const cosVelocityFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
cosVelocityFvPatchVectorField (const cosVelocityFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
void setPatchVelocities (vectorField &pV)
virtual void updateCoeffs ()
virtual void write (Ostream &) const
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchVectorField &pf, const labelList &ll)
Protected Attributes
vector A_
scalar H_
vector Hdirection_
scalar omega0_
scalar phi0_
scalar minZ_
Detailed Description
Definition at line 77 of file cosVelocityFvPatchVectorField.H.
Constructor & Destructor Documentation
cosVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 36 of file cosVelocityFvPatchVectorField.C.
Referenced by cosVelocityFvPatchVectorField::clone().
cosVelocityFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 82 of file cosVelocityFvPatchVectorField.C.
cosVelocityFvPatchVectorField (const cosVelocityFvPatchVectorField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 59 of file cosVelocityFvPatchVectorField.C.
cosVelocityFvPatchVectorField (const cosVelocityFvPatchVectorField & ptpsf)
Definition at line 121 of file cosVelocityFvPatchVectorField.C.
cosVelocityFvPatchVectorField (const cosVelocityFvPatchVectorField & ptpsf, const DimensionedField< vector, volMesh > & iF)
Definition at line 139 of file cosVelocityFvPatchVectorField.C.
Member Function Documentation
TypeName ("cosVelocity")
virtual tmp<fvPatchVectorField > clone () const [inline, virtual]
Definition at line 143 of file cosVelocityFvPatchVectorField.H.
References cosVelocityFvPatchVectorField::cosVelocityFvPatchVectorField().
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const [inline, virtual]
Definition at line 160 of file cosVelocityFvPatchVectorField.H.
References cosVelocityFvPatchVectorField::cosVelocityFvPatchVectorField().
void setPatchVelocities (vectorField & pV)
Definition at line 173 of file cosVelocityFvPatchVectorField.C.
References cosVelocityFvPatchVectorField::A_, forAll(), cosVelocityFvPatchVectorField::H_, cosVelocityFvPatchVectorField::Hdirection_, cosVelocityFvPatchVectorField::minZ_, cosVelocityFvPatchVectorField::omega0_, and cosVelocityFvPatchVectorField::phi0_.
Referenced by cosVelocityFvPatchVectorField::updateCoeffs().
void updateCoeffs () [virtual]
Definition at line 191 of file cosVelocityFvPatchVectorField.C.
References cosVelocityFvPatchVectorField::setPatchVelocities().
void write (Ostream & os) const [virtual]
Definition at line 206 of file cosVelocityFvPatchVectorField.C.
References cosVelocityFvPatchVectorField::A_, cosVelocityFvPatchVectorField::H_, cosVelocityFvPatchVectorField::Hdirection_, cosVelocityFvPatchVectorField::minZ_, cosVelocityFvPatchVectorField::omega0_, and cosVelocityFvPatchVectorField::phi0_.
void autoMap (const fvPatchFieldMapper & m) [virtual]
Definition at line 160 of file cosVelocityFvPatchVectorField.C.
void rmap (const fvPatchVectorField & pf, const labelList & ll) [virtual]
Definition at line 167 of file cosVelocityFvPatchVectorField.C.
Member Data Documentation
vector A_ [protected]
Definition at line 86 of file cosVelocityFvPatchVectorField.H.
Referenced by cosVelocityFvPatchVectorField::setPatchVelocities(), and cosVelocityFvPatchVectorField::write().
scalar H_ [protected]
Definition at line 89 of file cosVelocityFvPatchVectorField.H.
Referenced by cosVelocityFvPatchVectorField::setPatchVelocities(), and cosVelocityFvPatchVectorField::write().
vector Hdirection_ [protected]
Definition at line 92 of file cosVelocityFvPatchVectorField.H.
Referenced by cosVelocityFvPatchVectorField::setPatchVelocities(), and cosVelocityFvPatchVectorField::write().
scalar omega0_ [protected]
Definition at line 95 of file cosVelocityFvPatchVectorField.H.
Referenced by cosVelocityFvPatchVectorField::setPatchVelocities(), and cosVelocityFvPatchVectorField::write().
scalar phi0_ [protected]
Definition at line 98 of file cosVelocityFvPatchVectorField.H.
Referenced by cosVelocityFvPatchVectorField::setPatchVelocities(), and cosVelocityFvPatchVectorField::write().
scalar minZ_ [protected]
Definition at line 101 of file cosVelocityFvPatchVectorField.H.
Referenced by cosVelocityFvPatchVectorField::setPatchVelocities(), and cosVelocityFvPatchVectorField::write().
The documentation for this class was generated from the following files:
QGD/BCs/cosVelocity/cosVelocityFvPatchVectorField.H
QGD/BCs/cosVelocity/cosVelocityFvPatchVectorField.C
$mathjax