QGDsolver: QGDsolver: GaussVolPointBase Class Reference
GaussVolPointBase Class Reference
Public Member Functions
GaussVolPointBase (const fvMesh &mesh)
~GaussVolPointBase ()
void faceGrad (const volScalarField &vF, surfaceVectorField &gradf)
void faceGrad (const volVectorField &vF, surfaceTensorField &gradf)
void faceDiv (const volVectorField &vVF, surfaceScalarField &divf)
void faceDiv (const volTensorField &vTF, surfaceVectorField &divf)
Detailed Description
Definition at line 16 of file GaussVolPointBase.H.
Constructor & Destructor Documentation
GaussVolPointBase (const fvMesh & mesh)
Definition at line 11 of file GaussVolPointBase.C.
~GaussVolPointBase ()
Definition at line 20 of file GaussVolPointBase.C.
Member Function Documentation
void faceGrad (const volScalarField & vF, surfaceVectorField & gradf)
Reimplemented from GaussVolPointBase1D.
Definition at line 24 of file GaussVolPointBase.C.
Referenced by GaussVolPointBase::faceGrad(), and GaussVolPoint::Grad().
void faceGrad (const volVectorField & vF, surfaceTensorField & gradf)
Reimplemented from GaussVolPointBase1D.
Definition at line 42 of file GaussVolPointBase.C.
References GaussVolPointBase::faceGrad().
void faceDiv (const volVectorField & vVF, surfaceScalarField & divf)
Reimplemented from GaussVolPointBase1D.
Definition at line 93 of file GaussVolPointBase.C.
Referenced by GaussVolPoint::Div(), and GaussVolPointBase::faceDiv().
void faceDiv (const volTensorField & vTF, surfaceVectorField & divf)
Reimplemented from GaussVolPointBase1D.
Definition at line 112 of file GaussVolPointBase.C.
References GaussVolPointBase::faceDiv().
The documentation for this class was generated from the following files:
QGD/fvsc/GaussVolPoint/GaussVolPointBase.H
QGD/fvsc/GaussVolPoint/GaussVolPointBase.C
$mathjax