QGDsolver: QGDsolver: leastSquares Class Reference
leastSquares Class Reference
Public Member Functions
TypeName ("leastSquares")
leastSquares (const IOobject &)
~leastSquares ()
tmp< surfaceVectorField > Grad (const volScalarField &iF)
tmp< surfaceTensorField > Grad (const volVectorField &iVF)
tmp< surfaceScalarField > Div (const volVectorField &iVF)
tmp< surfaceVectorField > Div (const volTensorField &iTF)
Detailed Description
Definition at line 68 of file leastSquaresStencil.H.
Constructor & Destructor Documentation
leastSquares (const IOobject & io)
Definition at line 55 of file leastSquaresStencil.C.
References forAll(), leastSquaresBase::internalDegFaces_, fvscStencil::mesh_, leastSquaresBase::procDegFaces_, and leastSquaresBase::procPairs_.
~leastSquares ()
Definition at line 132 of file leastSquaresStencil.C.
Member Function Documentation
TypeName ("leastSquares")
Reimplemented from fvscStencil.
Foam::tmp< Foam::surfaceVectorField > Grad (const volScalarField & iF) [virtual]
Reimplemented from fvscStencil.
Definition at line 49 of file extendedFaceStencilScalarGrad.C.
References leastSquaresBase::corAddr_, leastSquaresBase::corCellIds_, leastSquaresBase::corProcIds_, leastSquaresBase::corStart_, forAll(), leastSquaresBase::GdfAll_, leastSquaresBase::internalDegFaces_, fvscStencil::mesh_, leastSquaresBase::myProcPatchCells_, leastSquaresBase::neiEnd_, leastSquaresBase::neighbourCells_, leastSquaresBase::neigProcs_, leastSquaresBase::neiStart_, fvscStencil::nf_, leastSquaresBase::nProcPatches_, leastSquaresBase::ownEnd_, leastSquaresBase::procDegFaces_, leastSquaresBase::procGdf_, leastSquaresBase::procPairs_, leastSquaresBase::procWf2_, and leastSquaresBase::wf2All_.
Referenced by leastSquares::Div(), and leastSquares::Grad().
Foam::tmp< Foam::surfaceTensorField > Grad (const volVectorField & iVF) [virtual]
Reimplemented from fvscStencil.
Definition at line 142 of file leastSquaresStencil.C.
References forAll(), leastSquares::Grad(), fvscStencil::mesh_, and fvscStencil::nf_.
Foam::tmp< Foam::surfaceScalarField > Div (const volVectorField & iVF) [virtual]
Reimplemented from fvscStencil.
Definition at line 201 of file leastSquaresStencil.C.
References forAll(), leastSquares::Grad(), fvscStencil::mesh_, and fvscStencil::nf_.
Foam::tmp< Foam::surfaceVectorField > Div (const volTensorField & iTF) [virtual]
Reimplemented from fvscStencil.
Definition at line 233 of file leastSquaresStencil.C.
References forAll(), leastSquares::Grad(), fvscStencil::mesh_, and fvscStencil::nf_.
The documentation for this class was generated from the following files:
QGD/fvsc/leastSquares/leastSquaresStencil.H
QGD/fvsc/leastSquares/extendedFaceStencilScalarGrad.C
QGD/fvsc/leastSquares/leastSquaresStencil.C
$mathjax