QGDsolver: QGDsolver: QGDThermo Class Reference
QGDThermo Class Reference
Public Member Functions
TypeName ("QGDThermo")
QGDThermo (const fvMesh &mesh, const dictionary &dict)
virtual ~QGDThermo ()
virtual const volScalarField & c () const =0
virtual const volScalarField & p () const =0
virtual tmp< volScalarField > rho () const =0
virtual tmp< volScalarField > mu () const =0
const volScalarField & hQGD () const
const volScalarField & tauQGD () const
const surfaceScalarField & hQGDf () const
const surfaceScalarField & tauQGDf () const
const volScalarField & muQGD () const
const volScalarField & alphauQGD () const
const volScalarField & aQGD () const
const surfaceScalarField & aQGDf () const
Switch implicitDiffusion () const
virtual bool read ()
Protected Member Functions
qgd::QGDCoeffs & qgdCoeffs ()
void correctQGD (volScalarField &mu, volScalarField &alphau)
Detailed Description
Definition at line 55 of file QGDThermo.H.
Constructor & Destructor Documentation
QGDThermo (const fvMesh & mesh, const dictionary & dict)
Definition at line 40 of file QGDThermo.C.
~QGDThermo () [virtual]
Definition at line 57 of file QGDThermo.C.
Member Function Documentation
Foam::qgd::QGDCoeffs & qgdCoeffs () [protected]
Definition at line 140 of file QGDThermo.C.
Referenced by twoPhaseIcoQGDThermo::correct(), and twoPhaseIcoQGDThermo::validateQGDCoeffs().
void correctQGD (volScalarField & mu, volScalarField & alphau) [protected]
Definition at line 76 of file QGDThermo.C.
References QGDThermo::alphauQGD(), forAll(), and QGDThermo::muQGD().
TypeName ("QGDThermo")
Reimplemented in psiQGDReactionThermo, psiQGDThermo, rhoQGDThermo, and twoPhaseIcoQGDThermo.
virtual const volScalarField& c () const [pure virtual]
Implemented in psiQGDThermo, rhoQGDThermo, and twoPhaseIcoQGDThermo.
Referenced by varScModel6::correct(), varScModel5::correct(), constScPrModel2::correct(), constScPrModel1n::correct(), and constScPrModel1::correct().
virtual const volScalarField& p () const [pure virtual]
Implemented in psiQGDThermo, rhoQGDThermo, and twoPhaseIcoQGDThermo.
Referenced by varScModel6::correct(), varScModel5::correct(), constScPrModel2::correct(), constScPrModel1n::correct(), and constScPrModel1::correct().
virtual tmp<volScalarField> rho () const [pure virtual]
Implemented in psiQGDThermo, rhoQGDThermo, and twoPhaseIcoQGDThermo.
Referenced by twoPhaseConstTau::correct(), varScModel6::correct(), varScModel5::correct(), and H2bynuQHD::correct().
virtual tmp<volScalarField> mu () const [pure virtual]
Implemented in psiQGDThermo, rhoQGDThermo, and twoPhaseIcoQGDThermo.
Referenced by twoPhaseConstTau::correct(), H2bynuQHD::correct(), and constScPrModel2::correct().
const Foam::volScalarField & hQGD () const
Definition at line 105 of file QGDThermo.C.
const Foam::volScalarField & tauQGD () const
Definition at line 110 of file QGDThermo.C.
const Foam::surfaceScalarField & hQGDf () const
Definition at line 115 of file QGDThermo.C.
const Foam::surfaceScalarField & tauQGDf () const
Definition at line 120 of file QGDThermo.C.
const Foam::volScalarField & muQGD () const
Definition at line 125 of file QGDThermo.C.
Referenced by QGDThermo::correctQGD().
const Foam::volScalarField & alphauQGD () const
Definition at line 130 of file QGDThermo.C.
Referenced by QGDThermo::correctQGD().
const volScalarField& aQGD () const
const surfaceScalarField& aQGDf () const
Foam::Switch implicitDiffusion () const
Definition at line 135 of file QGDThermo.C.
bool read () [virtual]
Reimplemented in psiQGDThermo, rhoQGDThermo, and twoPhaseIcoQGDThermo.
Definition at line 62 of file QGDThermo.C.
Referenced by twoPhaseIcoQGDThermo::read(), rhoQGDThermo::read(), and psiQGDThermo::read().
The documentation for this class was generated from the following files:
QGD/thermoModels/QGDThermo/QGDThermo.H
QGD/thermoModels/QGDThermo/QGDThermo.C
$mathjax