QGDsolver: QGDsolver: qhdFluxFvPatchScalarField Class Reference
qhdFluxFvPatchScalarField Class Reference
Public Member Functions
TypeName ("qhdFlux")
qhdFluxFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
qhdFluxFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
qhdFluxFvPatchScalarField (const qhdFluxFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
qhdFluxFvPatchScalarField (const qhdFluxFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
qhdFluxFvPatchScalarField (const qhdFluxFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
Definition at line 66 of file qhdFluxFvPatchScalarField.H.
Constructor & Destructor Documentation
qhdFluxFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 35 of file qhdFluxFvPatchScalarField.C.
Referenced by qhdFluxFvPatchScalarField::clone().
qhdFluxFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 45 of file qhdFluxFvPatchScalarField.C.
qhdFluxFvPatchScalarField (const qhdFluxFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 72 of file qhdFluxFvPatchScalarField.C.
qhdFluxFvPatchScalarField (const qhdFluxFvPatchScalarField & wbppsf)
Definition at line 119 of file qhdFluxFvPatchScalarField.C.
qhdFluxFvPatchScalarField (const qhdFluxFvPatchScalarField & wbppsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 128 of file qhdFluxFvPatchScalarField.C.
Member Function Documentation
TypeName ("qhdFlux")
virtual tmp<fvPatchScalarField> clone () const [inline, virtual]
Definition at line 112 of file qhdFluxFvPatchScalarField.H.
References qhdFluxFvPatchScalarField::qhdFluxFvPatchScalarField().
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const [inline, virtual]
Definition at line 129 of file qhdFluxFvPatchScalarField.H.
References qhdFluxFvPatchScalarField::qhdFluxFvPatchScalarField().
void updateCoeffs () [virtual]
Definition at line 156 of file qhdFluxFvPatchScalarField.C.
References rhof, and tauQGDf.
void write (Ostream & os) const [virtual]
Definition at line 219 of file qhdFluxFvPatchScalarField.C.
The documentation for this class was generated from the following files:
QGD/BCs/qhdFlux/qhdFluxFvPatchScalarField.H
QGD/BCs/qhdFlux/qhdFluxFvPatchScalarField.C
$mathjax