QGDsolver: QGDsolver: twoPhaseIcoQGDThermo Class Reference
twoPhaseIcoQGDThermo Class Reference
Public Member Functions
TypeName ("twoPhaseIcoQGDThermo")
twoPhaseIcoQGDThermo (const fvMesh &, const volVectorField &U)
virtual ~twoPhaseIcoQGDThermo ()
bool read ()
virtual const volScalarField & p () const
volScalarField & p ()
virtual tmp< volScalarField > rho () const
virtual tmp< volScalarField > mu () const
virtual const volScalarField & c () const
virtual void correct ()
Protected Member Functions
twoPhaseIcoQGDThermo (const twoPhaseIcoQGDThermo &)
void validateQGDCoeffs ()
Protected Attributes
volScalarField p_
Detailed Description
Definition at line 58 of file twoPhaseIcoQGDThermo.H.
Constructor & Destructor Documentation
twoPhaseIcoQGDThermo (const twoPhaseIcoQGDThermo &) [protected]
twoPhaseIcoQGDThermo (const fvMesh & mesh, const volVectorField & U)
Definition at line 42 of file twoPhaseIcoQGDThermo.C.
References twoPhaseIcoQGDThermo::read(), and twoPhaseIcoQGDThermo::validateQGDCoeffs().
~twoPhaseIcoQGDThermo () [virtual]
Definition at line 78 of file twoPhaseIcoQGDThermo.C.
Member Function Documentation
void validateQGDCoeffs () [protected]
Definition at line 84 of file twoPhaseIcoQGDThermo.C.
References QGDThermo::qgdCoeffs().
Referenced by twoPhaseIcoQGDThermo::twoPhaseIcoQGDThermo().
TypeName ("twoPhaseIcoQGDThermo")
Reimplemented from QGDThermo.
bool read () [virtual]
Reimplemented from QGDThermo.
Definition at line 94 of file twoPhaseIcoQGDThermo.C.
References QGDThermo::read().
Referenced by twoPhaseIcoQGDThermo::twoPhaseIcoQGDThermo().
const Foam::volScalarField & p () const [virtual]
Implements QGDThermo.
Definition at line 105 of file twoPhaseIcoQGDThermo.C.
References twoPhaseIcoQGDThermo::p_.
Foam::volScalarField & p ()
Definition at line 110 of file twoPhaseIcoQGDThermo.C.
References twoPhaseIcoQGDThermo::p_.
Foam::tmp< Foam::volScalarField > rho () const [virtual]
Implements QGDThermo.
Definition at line 121 of file twoPhaseIcoQGDThermo.C.
References constTwoPhaseProperties::rho1(), and constTwoPhaseProperties::rho2().
Foam::tmp< Foam::volScalarField > mu () const [virtual]
Implements QGDThermo.
Definition at line 126 of file twoPhaseIcoQGDThermo.C.
References constTwoPhaseProperties::nu1(), constTwoPhaseProperties::nu2(), constTwoPhaseProperties::rho1(), and constTwoPhaseProperties::rho2().
const Foam::volScalarField & c () const [virtual]
Implements QGDThermo.
Definition at line 115 of file twoPhaseIcoQGDThermo.C.
void correct () [virtual]
Reimplemented from qInterfaceProperties.
Definition at line 131 of file twoPhaseIcoQGDThermo.C.
References QGDCoeffs::correct(), and QGDThermo::qgdCoeffs().
Member Data Documentation
volScalarField p_ [protected]
Definition at line 72 of file twoPhaseIcoQGDThermo.H.
Referenced by twoPhaseIcoQGDThermo::p().
The documentation for this class was generated from the following files:
TwoPhaseQGD/thermoModels/twoPhaseIcoQGDThermo/twoPhaseIcoQGDThermo.H
TwoPhaseQGD/thermoModels/twoPhaseIcoQGDThermo/twoPhaseIcoQGDThermo.C
$mathjax