QGDsolver: QGDsolver: varScModel5 Class Reference
varScModel5 Class Reference
Public Member Functions
TypeName ("varScModel5")
varScModel5 (const IOobject &io, const fvMesh &mesh, const dictionary &dict)
~varScModel5 ()
void correct (const QGDThermo &)
Protected Attributes
scalar smoothCoeff_
scalar rC_
scalar minSc_
scalar maxSc_
scalar badQualitySc_
scalar qgdAspectRatioThreshold_
scalar constSc_
scalarField cqSc_
autoPtr< cellSet > constScCellSetPtr_
Detailed Description
Definition at line 59 of file varScModel5.H.
Constructor & Destructor Documentation
varScModel5 (const IOobject & io, const fvMesh & mesh, const dictionary & dict)
Definition at line 54 of file varScModel5.C.
References forAll().
~varScModel5 ()
Definition at line 193 of file varScModel5.C.
Member Function Documentation
TypeName ("varScModel5")
Reimplemented from QGDCoeffs.
void correct (const QGDThermo & qgdThermo) [virtual]
Reimplemented from QGDCoeffs.
Definition at line 198 of file varScModel5.C.
References QGDCoeffs::alphauQGD_, QGDCoeffs::aQGD_, QGDThermo::c(), varScModel5::constSc_, varScModel5::constScCellSetPtr_, varScModel5::cqSc_, forAll(), Foam::fvsc::grad(), QGDCoeffs::hQGD_, QGDCoeffs::hQGDf_, varScModel5::maxSc_, varScModel5::minSc_, QGDCoeffs::muQGD_, QGDThermo::p(), p, QGDCoeffs::PrQGD_, varScModel5::rC_, QGDThermo::rho(), rho(), QGDCoeffs::runTime_, QGDCoeffs::ScQGD_, varScModel5::smoothCoeff_, QGDCoeffs::tauQGD_, and QGDCoeffs::tauQGDf_.
Member Data Documentation
scalar smoothCoeff_ [protected]
Definition at line 64 of file varScModel5.H.
Referenced by varScModel5::correct().
scalar rC_ [protected]
Definition at line 65 of file varScModel5.H.
Referenced by varScModel5::correct().
scalar minSc_ [protected]
Definition at line 66 of file varScModel5.H.
Referenced by varScModel5::correct().
scalar maxSc_ [protected]
Definition at line 67 of file varScModel5.H.
Referenced by varScModel5::correct().
scalar badQualitySc_ [protected]
Definition at line 68 of file varScModel5.H.
scalar qgdAspectRatioThreshold_ [protected]
Definition at line 69 of file varScModel5.H.
scalar constSc_ [protected]
Definition at line 70 of file varScModel5.H.
Referenced by varScModel5::correct().
scalarField cqSc_ [protected]
Definition at line 72 of file varScModel5.H.
Referenced by varScModel5::correct().
autoPtr<cellSet> constScCellSetPtr_ [protected]
Definition at line 74 of file varScModel5.H.
Referenced by varScModel5::correct().
The documentation for this class was generated from the following files:
QGD/QGDCoeffs/varScModel5/varScModel5.H
QGD/QGDCoeffs/varScModel5/varScModel5.C
$mathjax