QGDsolver: QGDsolver: GaussVolPoint Class Reference
GaussVolPoint Class Reference
Public Member Functions
TypeName ("GaussVolPoint")
GaussVolPoint (const IOobject &)
~GaussVolPoint ()
tmp< surfaceVectorField > Grad (const volScalarField &iF)
tmp< surfaceTensorField > Grad (const volVectorField &iVF)
tmp< surfaceScalarField > Div (const volVectorField &iVF)
tmp< surfaceVectorField > Div (const volTensorField &iTF)
Detailed Description
Definition at line 57 of file GaussVolPointStencil.H.
Constructor & Destructor Documentation
GaussVolPoint (const IOobject & io)
Definition at line 50 of file GaussVolPointStencil.C.
~GaussVolPoint ()
Definition at line 57 of file GaussVolPointStencil.C.
Member Function Documentation
TypeName ("GaussVolPoint")
Reimplemented from fvscStencil.
Foam::tmp< Foam::surfaceVectorField > Grad (const volScalarField & iF) [virtual]
Reimplemented from fvscStencil.
Definition at line 67 of file GaussVolPointStencil.C.
References correctBoundaryConditions(), and GaussVolPointBase::faceGrad().
Foam::tmp< Foam::surfaceTensorField > Grad (const volVectorField & iVF) [virtual]
Reimplemented from fvscStencil.
Definition at line 85 of file GaussVolPointStencil.C.
References correctBoundaryConditions(), and GaussVolPointBase::faceGrad().
Foam::tmp< Foam::surfaceScalarField > Div (const volVectorField & iVF) [virtual]
Reimplemented from fvscStencil.
Definition at line 97 of file GaussVolPointStencil.C.
References correctBoundaryConditions(), and GaussVolPointBase::faceDiv().
Foam::tmp< Foam::surfaceVectorField > Div (const volTensorField & iTF) [virtual]
Reimplemented from fvscStencil.
Definition at line 115 of file GaussVolPointStencil.C.
References correctBoundaryConditions(), and GaussVolPointBase::faceDiv().
The documentation for this class was generated from the following files:
QGD/fvsc/GaussVolPoint/GaussVolPointStencil.H
QGD/fvsc/GaussVolPoint/GaussVolPointStencil.C
$mathjax