QGDsolver: QGDsolver: qgdFluxFvPatchScalarField Class Reference
qgdFluxFvPatchScalarField Class Reference
Public Member Functions
TypeName ("qgdFlux")
qgdFluxFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
qgdFluxFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
qgdFluxFvPatchScalarField (const qgdFluxFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
qgdFluxFvPatchScalarField (const qgdFluxFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
qgdFluxFvPatchScalarField (const qgdFluxFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
Definition at line 66 of file qgdFluxFvPatchScalarField.H.
Constructor & Destructor Documentation
qgdFluxFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 35 of file qgdFluxFvPatchScalarField.C.
Referenced by qgdFluxFvPatchScalarField::clone().
qgdFluxFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 45 of file qgdFluxFvPatchScalarField.C.
qgdFluxFvPatchScalarField (const qgdFluxFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 72 of file qgdFluxFvPatchScalarField.C.
qgdFluxFvPatchScalarField (const qgdFluxFvPatchScalarField & wbppsf)
Definition at line 119 of file qgdFluxFvPatchScalarField.C.
qgdFluxFvPatchScalarField (const qgdFluxFvPatchScalarField & wbppsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 128 of file qgdFluxFvPatchScalarField.C.
Member Function Documentation
TypeName ("qgdFlux")
virtual tmp<fvPatchScalarField> clone () const [inline, virtual]
Definition at line 112 of file qgdFluxFvPatchScalarField.H.
References qgdFluxFvPatchScalarField::qgdFluxFvPatchScalarField().
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const [inline, virtual]
Definition at line 129 of file qgdFluxFvPatchScalarField.H.
References qgdFluxFvPatchScalarField::qgdFluxFvPatchScalarField().
void updateCoeffs () [virtual]
Definition at line 156 of file qgdFluxFvPatchScalarField.C.
References tauQGDf.
void write (Ostream & os) const [virtual]
Definition at line 208 of file qgdFluxFvPatchScalarField.C.
The documentation for this class was generated from the following files:
QGD/BCs/qgdFlux/qgdFluxFvPatchScalarField.H
QGD/BCs/qgdFlux/qgdFluxFvPatchScalarField.C
$mathjax