QGDsolver: QGDsolver: constTwoPhaseProperties Class Reference
constTwoPhaseProperties Class Reference
Public Member Functions
constTwoPhaseProperties (const dictionary &dict, const word &phase1name, const word &phase2name)
~constTwoPhaseProperties ()
const dimensionedScalar & nu1 () const
const dimensionedScalar & nu2 () const
const dimensionedScalar & rho1 () const
const dimensionedScalar & rho2 () const
const dimensionedScalar & Tau1 () const
const dimensionedScalar & Tau2 () const
Detailed Description
Definition at line 12 of file constTwoPhaseProperties.H.
Constructor & Destructor Documentation
constTwoPhaseProperties (const dictionary & dict, const word & phase1name, const word & phase2name)
Definition at line 6 of file constTwoPhaseProperties.C.
~constTwoPhaseProperties ()
Definition at line 24 of file constTwoPhaseProperties.C.
Member Function Documentation
const Foam::dimensionedScalar & nu1 () const
Definition at line 30 of file constTwoPhaseProperties.C.
Referenced by twoPhaseIcoQGDThermo::mu().
const Foam::dimensionedScalar & nu2 () const
Definition at line 35 of file constTwoPhaseProperties.C.
Referenced by twoPhaseIcoQGDThermo::mu().
const Foam::dimensionedScalar & rho1 () const
Definition at line 40 of file constTwoPhaseProperties.C.
Referenced by twoPhaseIcoQGDThermo::mu(), and twoPhaseIcoQGDThermo::rho().
const Foam::dimensionedScalar & rho2 () const
Definition at line 45 of file constTwoPhaseProperties.C.
Referenced by twoPhaseIcoQGDThermo::mu(), and twoPhaseIcoQGDThermo::rho().
const Foam::dimensionedScalar & Tau1 () const
Definition at line 50 of file constTwoPhaseProperties.C.
Referenced by twoPhaseConstTau::correct().
const Foam::dimensionedScalar & Tau2 () const
Definition at line 55 of file constTwoPhaseProperties.C.
Referenced by twoPhaseConstTau::correct().
The documentation for this class was generated from the following files:
TwoPhaseQGD/thermoModels/twoPhaseIcoQGDThermo/constTwoPhaseProperties.H
TwoPhaseQGD/thermoModels/twoPhaseIcoQGDThermo/constTwoPhaseProperties.C
$mathjax