QGDsolver: QGDsolver: fvscStencil Class Reference
fvscStencil Class Reference
Public Member Functions
TypeName ("fvscStencil")
declareRunTimeSelectionTable (autoPtr, fvscStencil, components,(const IOobject &io),(io))
fvscStencil (const IOobject &io)
virtual ~fvscStencil ()
virtual tmp< surfaceVectorField > Grad (const volScalarField &vF)
virtual tmp< surfaceTensorField > Grad (const volVectorField &iVF)
virtual tmp< surfaceScalarField > Div (const volVectorField &iVF)
virtual tmp< surfaceVectorField > Div (const volTensorField &iTF)
virtual bool writeData (Ostream &) const
Static Public Member Functions
static autoPtr< fvscStencil > New (const word &name, const fvMesh &mesh)
static fvscStencil & lookupOrNew (const word &nname, const fvMesh &mesh)
Protected Attributes
const fvMesh & mesh_
const Time & runTime_
surfaceVectorField nf_
Static Protected Attributes
static PtrList< fvscStencil > stencils_
Detailed Description
Definition at line 49 of file fvscStencil.H.
Constructor & Destructor Documentation
fvscStencil (const IOobject & io)
Definition at line 115 of file fvscStencil.C.
References fvscStencil::nf_.
~fvscStencil () [virtual]
Definition at line 129 of file fvscStencil.C.
Member Function Documentation
TypeName ("fvscStencil")
Reimplemented in GaussVolPoint, leastSquares, leastSquaresOpt, and reduced.
declareRunTimeSelectionTable (autoPtr , fvscStencil , components , (const IOobject &io) , (io))
autoPtr< fvscStencil > New (const word & name, const fvMesh & mesh) [static]
Definition at line 55 of file fvscStencil.C.
Referenced by fvscStencil::lookupOrNew().
fvscStencil & lookupOrNew (const word & nname, const fvMesh & mesh) [static]
Definition at line 94 of file fvscStencil.C.
References fvscStencil::New().
Referenced by Foam::fvsc::div(), and Foam::fvsc::grad().
virtual tmp<surfaceVectorField> Grad (const volScalarField & vF) [inline, virtual]
Reimplemented in GaussVolPoint, leastSquares, leastSquaresOpt, and reduced.
Definition at line 108 of file fvscStencil.H.
Referenced by Foam::fvsc::grad().
virtual tmp<surfaceTensorField> Grad (const volVectorField & iVF) [inline, virtual]
Reimplemented in GaussVolPoint, leastSquares, leastSquaresOpt, and reduced.
Definition at line 115 of file fvscStencil.H.
virtual tmp<surfaceScalarField> Div (const volVectorField & iVF) [inline, virtual]
Reimplemented in GaussVolPoint, leastSquares, leastSquaresOpt, and reduced.
Definition at line 122 of file fvscStencil.H.
Referenced by Foam::fvsc::div().
virtual tmp<surfaceVectorField> Div (const volTensorField & iTF) [inline, virtual]
Reimplemented in GaussVolPoint, leastSquares, leastSquaresOpt, and reduced.
Definition at line 129 of file fvscStencil.H.
virtual bool writeData (Ostream &) const [inline, virtual]
Definition at line 136 of file fvscStencil.H.
Member Data Documentation
const fvMesh& mesh_ [protected]
Definition at line 55 of file fvscStencil.H.
Referenced by leastSquaresOpt::Div(), leastSquares::Div(), leastSquaresOpt::Grad(), leastSquares::Grad(), and leastSquares::leastSquares().
const Time& runTime_ [protected]
Definition at line 58 of file fvscStencil.H.
surfaceVectorField nf_ [protected]
Definition at line 61 of file fvscStencil.H.
Referenced by reduced::Div(), leastSquaresOpt::Div(), leastSquares::Div(), fvscStencil::fvscStencil(), reduced::Grad(), leastSquaresOpt::Grad(), and leastSquares::Grad().
PtrList< fvscStencil > stencils_ [static, protected]
Definition at line 64 of file fvscStencil.H.
The documentation for this class was generated from the following files:
QGD/fvsc/fvscStencil/fvscStencil.H
QGD/fvsc/fvscStencil/fvscStencil.C
$mathjax