QGDsolver: QGDsolver: psiQGDThermo Class Reference
psiQGDThermo Class Reference
Public Member Functions
TypeName ("psiQGDThermo")
declareRunTimeSelectionTable (autoPtr, psiQGDThermo, fvMesh,(const fvMesh &mesh, const word &phaseName),(mesh, phaseName))
psiQGDThermo (const fvMesh &, const word &phaseName)
psiQGDThermo (const fvMesh &, const word &phaseName, const word &dictName)
virtual ~psiQGDThermo ()
bool read ()
const volScalarField & c () const
virtual const volScalarField & p () const
volScalarField & p ()
virtual tmp< volScalarField > rho () const
virtual tmp< volScalarField > mu () const
Static Public Member Functions
static autoPtr< psiQGDThermo > New (const fvMesh &mesh, const word &phaseName=word::null)
static autoPtr< psiQGDThermo > New (const fvMesh &mesh, const word &phaseName, const word &dictName)
Protected Member Functions
psiQGDThermo (const psiQGDThermo &)
Protected Attributes
volScalarField c_
volScalarField gamma_
Detailed Description
Definition at line 56 of file psiQGDThermo.H.
Constructor & Destructor Documentation
psiQGDThermo (const psiQGDThermo &) [protected]
psiQGDThermo (const fvMesh & mesh, const word & phaseName)
Definition at line 53 of file psiQGDThermo.C.
References psiQGDThermo::read().
psiQGDThermo (const fvMesh & mesh, const word & phaseName, const word & dictName)
Definition at line 71 of file psiQGDThermo.C.
References psiQGDThermo::read().
~psiQGDThermo () [virtual]
Definition at line 114 of file psiQGDThermo.C.
Member Function Documentation
TypeName ("psiQGDThermo")
Reimplemented from QGDThermo.
Reimplemented in psiQGDReactionThermo.
declareRunTimeSelectionTable (autoPtr , psiQGDThermo , fvMesh , (const fvMesh &mesh, const word &phaseName) , (mesh, phaseName))
Reimplemented in psiQGDReactionThermo.
Foam::autoPtr< Foam::psiQGDThermo > New (const fvMesh & mesh, const word & phaseName = word::null) [static]
Reimplemented in psiQGDReactionThermo.
Definition at line 94 of file psiQGDThermo.C.
Foam::autoPtr< Foam::psiQGDThermo > New (const fvMesh & mesh, const word & phaseName, const word & dictName) [static]
Reimplemented in psiQGDReactionThermo.
Definition at line 103 of file psiQGDThermo.C.
bool read () [virtual]
Reimplemented from QGDThermo.
Definition at line 122 of file psiQGDThermo.C.
References QGDThermo::read().
Referenced by psiQGDThermo::psiQGDThermo().
const Foam::volScalarField & c () const [virtual]
Implements QGDThermo.
Definition at line 137 of file psiQGDThermo.C.
References psiQGDThermo::c_.
const Foam::volScalarField & p () const [virtual]
Implements QGDThermo.
Definition at line 142 of file psiQGDThermo.C.
Referenced by psiQGDThermo::p().
Foam::volScalarField & p ()
Definition at line 147 of file psiQGDThermo.C.
References psiQGDThermo::p().
Foam::tmp< Foam::volScalarField > rho () const [virtual]
Implements QGDThermo.
Definition at line 152 of file psiQGDThermo.C.
Foam::tmp< Foam::volScalarField > mu () const [virtual]
Implements QGDThermo.
Definition at line 157 of file psiQGDThermo.C.
Member Data Documentation
volScalarField c_ [protected]
Definition at line 69 of file psiQGDThermo.H.
Referenced by psiQGDThermo::c().
volScalarField gamma_ [protected]
Definition at line 72 of file psiQGDThermo.H.
The documentation for this class was generated from the following files:
QGD/thermoModels/psiQGDThermo/psiQGDThermo.H
QGD/thermoModels/psiQGDThermo/psiQGDThermo.C
$mathjax