QGDsolver: QGDsolver: mQhdFluxFvPatchScalarField Class Reference
mQhdFluxFvPatchScalarField Class Reference
Public Member Functions
TypeName ("mQhdFlux")
mQhdFluxFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
mQhdFluxFvPatchScalarField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
mQhdFluxFvPatchScalarField (const mQhdFluxFvPatchScalarField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
mQhdFluxFvPatchScalarField (const mQhdFluxFvPatchScalarField &)
virtual tmp< fvPatchScalarField > clone () const
mQhdFluxFvPatchScalarField (const mQhdFluxFvPatchScalarField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
Definition at line 66 of file mQhdFluxFvPatchScalarField.H.
Constructor & Destructor Documentation
mQhdFluxFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 35 of file mQhdFluxFvPatchScalarField.C.
Referenced by mQhdFluxFvPatchScalarField::clone().
mQhdFluxFvPatchScalarField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 45 of file mQhdFluxFvPatchScalarField.C.
mQhdFluxFvPatchScalarField (const mQhdFluxFvPatchScalarField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 72 of file mQhdFluxFvPatchScalarField.C.
mQhdFluxFvPatchScalarField (const mQhdFluxFvPatchScalarField & wbppsf)
Definition at line 119 of file mQhdFluxFvPatchScalarField.C.
mQhdFluxFvPatchScalarField (const mQhdFluxFvPatchScalarField & wbppsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 128 of file mQhdFluxFvPatchScalarField.C.
Member Function Documentation
TypeName ("mQhdFlux")
virtual tmp<fvPatchScalarField> clone () const [inline, virtual]
Definition at line 112 of file mQhdFluxFvPatchScalarField.H.
References mQhdFluxFvPatchScalarField::mQhdFluxFvPatchScalarField().
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const [inline, virtual]
Definition at line 129 of file mQhdFluxFvPatchScalarField.H.
References mQhdFluxFvPatchScalarField::mQhdFluxFvPatchScalarField().
void updateCoeffs () [virtual]
Definition at line 156 of file mQhdFluxFvPatchScalarField.C.
References coeffp(), and phiwm().
void write (Ostream & os) const [virtual]
Definition at line 197 of file mQhdFluxFvPatchScalarField.C.
The documentation for this class was generated from the following files:
TwoPhaseQGD/BCs/mQhdFlux/mQhdFluxFvPatchScalarField.H
TwoPhaseQGD/BCs/mQhdFlux/mQhdFluxFvPatchScalarField.C
$mathjax