QGDsolver: QGDsolver: QGD/QGDcommon/createZeroSources.H File Reference
QGD/QGDcommon/createZeroSources.H File Reference
Functions
fvScalarMatrix rhoSu (rho, rho.dimensions()*dimVolume/dimTime)
fvVectorMatrix rhoUSu (U, rho.dimensions()*U.dimensions()*dimVolume/dimTime)
fvScalarMatrix rhoESu (e, rho.dimensions()*e.dimensions()*dimVolume/dimTime)
Function Documentation
fvScalarMatrix rhoSu (rho , rho.dimensions()*dimVolume/ dimTime)
fvVectorMatrix rhoUSu (U , rho.dimensions()*U.dimensions()*dimVolume/ dimTime)
Referenced by if(), and main().
fvScalarMatrix rhoESu (e , rho.dimensions()*e.dimensions()*dimVolume/ dimTime)
Referenced by if(), and main().
$mathjax