QGDsolver: QGDsolver: interQHDFoam/createFaceFields.H File Reference
interQHDFoam/createFaceFields.H File Reference
Functions
surfaceScalarField alpha1f ("alpha1f", linearInterpolate(alpha1))
surfaceScalarField alpha2f ("alpha2f", 1.0-alpha1f)
surfaceVectorField Uf ("Uf", linearInterpolate(U))
surfaceVectorField W1 ("Wf", linearInterpolate(U)*0.0)
surfaceVectorField W2 ("Wf", linearInterpolate(U)*0.0)
surfaceVectorField BdFrcf ("BdFrcf", linearInterpolate(BdFrc))
surfaceVectorField cFrcf ("cFrcf", linearInterpolate(cFrc))
surfaceScalarField muf ("muf", linearInterpolate(thermo.mu()*0.0))
Function Documentation
surfaceScalarField alpha1f ("alpha1f" , linearInterpolate(alpha1))
Referenced by main().
surfaceScalarField alpha2f ("alpha2f" , 1.0- alpha1f)
Referenced by main().
surfaceVectorField Uf ("Uf" , linearInterpolate(U))
surfaceVectorField W1 ("Wf" , linearInterpolate(U)*0. 0)
Referenced by main().
surfaceVectorField W2 ("Wf" , linearInterpolate(U)*0. 0)
Referenced by main().
surfaceVectorField BdFrcf ("BdFrcf" , linearInterpolate(BdFrc))
surfaceVectorField cFrcf ("cFrcf" , linearInterpolate(cFrc))
Referenced by main().
surfaceScalarField muf ("muf" , linearInterpolate(thermo.mu()*0.0))
$mathjax