QGDsolver: interQHDFoam/interQHDFoam.C File Reference
interQHDFoam.C File Reference
Solver for unsteady 3D turbulent flow of 2 incompressible immisicible fluids governed by quasi-hydrodynamic dynamic (QHD) equations.
Macros
#define NO_CONTROL
Functions
int main (int argc, char *argv[])
Detailed Description
Solver for unsteady 3D turbulent flow of 2 incompressible immisicible fluids governed by quasi-hydrodynamic dynamic (QHD) equations.
Original source file interQHDFoam.C
QHD system of equations has been developed by scientific group from Keldysh Institute of Applied Mathematics, see http://elizarova.imamod.ru/selection-of-papers.html
A comprehensive description of QGD equations and their applications can be found here:
Elizarova, T.G.
"Quasi-Gas Dynamic equations"
Springer, 2009
A brief of theory on QGD and QHD system of equations:
Elizarova, T.G. and Sheretov, Y.V.
"Theoretical and numerical analysis of quasi-gasdynamic and quasi-hydrodynamic
equations"
J. Computational Mathematics and Mathematical Physics, vol. 41, no. 2, pp 219-234,
2001
Developed by UniCFD group (www.unicfd.ru) of ISP RAS (www.ispras.ru).
Definition in file interQHDFoam.C.
Macro Definition Documentation
#define NO_CONTROL
Function Documentation
int main (int argc, char * argv[])
——–Start———
——–End——— # 102 "/home/cfd/4jenk/digitef-dev-1912-1/interQHDFoam/interQHDFoam.C" 2 /*
Update time step
Definition at line 59 of file interQHDFoam.C.
References alpha1f(), alpha2f(), BdFrc, cFrcf(), coeffp(), Foam::fvsc::div(), forAll(), Foam::fvsc::grad(), gradpf(), gradUf, implicitDiffusion(), muf, p, pEqn(), phi, phi1(), phi2(), phiAlpha1f(), phiAlpha2f(), phiRhofWf(), phiu, phiUfRhof(), phiw1(), phiw2(), phiwm(), phiwo1, phiwo2, phiWr(), Foam::qgdFlux(), Foam::qgdInterpolate(), rho(), rhoPhi(), solve(), T, thermo, U(), Uf, W1(), and W2().