QGDsolver: mulesQHDFoam/mulesQHDFoam.C File Reference
mulesQHDFoam.C File Reference
Solver for unsteady 3D turbulent flow of incompressible viscous fluid governed by quasi-hydrodynamic dynamic (QHD) equations. The temperature scalar transport equation is solved by MULES technology.
Macros
#define NO_CONTROL
Functions
int main (int argc, char *argv[])
Detailed Description
Solver for unsteady 3D turbulent flow of incompressible viscous fluid governed by quasi-hydrodynamic dynamic (QHD) equations. The temperature scalar transport equation is solved by MULES technology.
Original source file mulesQHDFoam.C
QHD system of equations has been developed by scientific group from Keldysh Institute of Applied Mathematics, see http://elizarova.imamod.ru/selection-of-papers.html
A comprehensive description of QGD equations and their applications can be found here:
Elizarova, T.G.
"Quasi-Gas Dynamic equations"
Springer, 2009
A brief of theory on QGD and QHD system of equations:
Elizarova, T.G. and Sheretov, Y.V.
"Theoretical and numerical analysis of quasi-gasdynamic and quasi-hydrodynamic
equations"
J. Computational Mathematics and Mathematical Physics, vol. 41, no. 2, pp 219-234,
2001
Developed by UniCFD group (www.unicfd.ru) of ISP RAS (www.ispras.ru).
MULES: Multidimensional universal limiter for explicit solution.
Solve a convective-only transport equation using an explicit universal multi-dimensional limiter. See https://www.openfoam.com/documentation/guides/latest/api/MULES_8H_source.html
Definition in file mulesQHDFoam.C.
Macro Definition Documentation
#define NO_CONTROL
Function Documentation
int main (int argc, char * argv[])
——–Start———
——–End———
P equation fluxes ——–Start——— ——–End———
——–Start———
——–End———
——–Start———
——–End——— # 85 "/home/cfd/4jenk/digitef-dev-1912-1/mulesQHDFoam/mulesQHDFoam.C" 2 #include "createTimeControls.H" pimpleControl pimple(mesh); turbulence->validate(); * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * // Courant numbers used to adjust the time-step scalar CoNum = 0.0; scalar meanCoNum = 0.0; Info << "\nStarting time loop\n" << endl;
while (runTime.run()) { /*
Update fields
——–Start———
——–End———
Definition at line 76 of file mulesQHDFoam.C.
References p, phi, phiTf(), Foam::qgdFlux(), T, Tf, turbulence, and U().