QGDsolver: mulesQHDFoam/updateFields.H File Reference
updateFields.H File Reference
Variables
gradUf = fvsc::grad(U)
gradWf = fvsc::grad(W)
gradTf = fvsc::grad(T)
muf = qgdInterpolate(turbulence->mu())
alphaf = qgdInterpolate(turbulence->alpha())
rhof = qgdInterpolate(rho)
Uf = qgdInterpolate(U)
Tf = qgdInterpolate(T)
BdFrc = beta*(T-T0)*g
BdFrcf = qgdInterpolate(BdFrc)
Hif = alphaf/rhof
Cpf = qgdInterpolate(thermo.Cp())
Variable Documentation
gradUf = fvsc::grad(U)
Definition at line 6 of file updateFields.H.
gradWf = fvsc::grad(W)
Definition at line 8 of file updateFields.H.
gradTf = fvsc::grad(T)
Definition at line 10 of file updateFields.H.
Referenced by if(), and main().
muf = qgdInterpolate(turbulence->mu())
Definition at line 17 of file updateFields.H.
alphaf = qgdInterpolate(turbulence->alpha())
Definition at line 18 of file updateFields.H.
rhof = qgdInterpolate(rho)
Definition at line 27 of file updateFields.H.
Referenced by qhdFluxFvPatchScalarField::updateCoeffs().
Uf = qgdInterpolate(U)
Definition at line 30 of file updateFields.H.
Referenced by if(), and main().
Tf = qgdInterpolate(T)
Definition at line 33 of file updateFields.H.
Referenced by if(), and main().
BdFrc = beta*(T-T0)*g
Definition at line 35 of file updateFields.H.
BdFrcf = qgdInterpolate(BdFrc)
Definition at line 36 of file updateFields.H.
Hif = alphaf/rhof
Definition at line 39 of file updateFields.H.
Referenced by forAll(), and main().
Cpf = qgdInterpolate(thermo.Cp())
Definition at line 42 of file updateFields.H.