QGDsolver: mulesQHDFoam/createFields.H File Reference
createFields.H File Reference
Functions
Info<< "\nReading
gravitationalProperties"
<< endl;IOdictionary
gravitationalProperties(IOobject("gravitationalProperties",
runTime.constant(), mesh,
IOobject::MUST_READ_IF_MODIFIED,
IOobject::NO_WRITE));const
dimensionedVector g(gravitationalProperties.lookup("g"));Info
<< "Reading thermophysical
properties\n"<< endl;autoPtr
< rhoQGDThermo > pThermo (rhoQGDThermo::New(mesh))
thermo correct ()
volVectorField U (IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh)
volScalarField T0 ("T0", T)
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), thermo.rho())
volVectorField W (IOobject("W", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), U)
dimensionedScalar beta ("beta", dimless/dimTemperature, thermo.subDict("mixture").subDict("transport"))
surfaceScalarField phiu ("phiu", mesh.Sf()&linearInterpolate(U))
surfaceScalarField phiwo ("phiwStar", mesh.Sf()&linearInterpolate(W))
surfaceScalarField phi ("phi", mesh.Sf()&(linearInterpolate(U)-linearInterpolate(W)))
surfaceScalarField phiRhof ("phiRhof", linearInterpolate(rho)*phi)
volVectorField BdFrc ("BdFrc", T *g *beta)
Switch implicitDiffusion (thermo.implicitDiffusion())
Variables
rhoQGDThermo & thermo = pThermo()
volScalarField & e = thermo.he()
volScalarField & p = thermo.p()
volScalarField & T = const_cast<volScalarField&>(thermo.T())
const surfaceScalarField & hQGDf = thermo.hQGDf()
const surfaceScalarField & tauQGDf = thermo.tauQGDf()
Info<< "Thermo corrected"
<< endl;autoPtr
< compressible::turbulenceModel > turbulence
Detailed Description
Original source file createFields.H
Creating fields for calculations SourceFile mulesQHDFoam.C
Definition in file createFields.H.
Function Documentation
Info<< "\nReading gravitationalProperties" << endl;IOdictionary gravitationalProperties(IOobject ("gravitationalProperties", runTime.constant(), mesh, IOobject::MUST_READ_IF_MODIFIED, IOobject::NO_WRITE));const dimensionedVector g(gravitationalProperties.lookup("g"));Info << "Reading thermophysical properties\n" << endl;autoPtr<rhoQGDThermo> pThermo (rhoQGDThermo:: Newmesh)
thermo correct ()
volVectorField U (IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE) , mesh)
volScalarField T0 ("T0" , T)
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , thermo. rho())
Referenced by if(), and main().
volVectorField W (IOobject("W", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE) , U)
dimensionedScalar beta ("beta" , dimless/ dimTemperature, thermo. subDict"mixture").subDict("transport")
surfaceScalarField phiu ("phiu" , mesh. Sf)&linearInterpolate(U)
surfaceScalarField phiwo ("phiwStar" , mesh. Sf)&linearInterpolate(W)
surfaceScalarField phi ("phi" , mesh. Sf)&(linearInterpolate(U)-linearInterpolate(W))
surfaceScalarField phiRhof ("phiRhof" , linearInterpolate(rho)* phi)
volVectorField BdFrc ("BdFrc" , T *g * beta)
Switch implicitDiffusion (thermo. implicitDiffusion())
Referenced by if(), and main().
Variable Documentation
rhoQGDThermo& thermo = pThermo()
Definition at line 47 of file createFields.H.
Referenced by forAll(), if(), and main().
volScalarField& e = thermo.he()
Definition at line 50 of file createFields.H.
Referenced by main().
volScalarField& p = thermo.p()
Definition at line 52 of file createFields.H.
Referenced by forAll(), and main().
volScalarField& T = const_cast<volScalarField&>(thermo.T())
Definition at line 53 of file createFields.H.
Referenced by powerLawTransport< Thermo >::alphah(), forAll(), if(), powerLawTransport< Thermo >::kappa(), and main().
const surfaceScalarField& hQGDf = thermo.hQGDf()
Definition at line 54 of file createFields.H.
Referenced by if(), and main().
const surfaceScalarField& tauQGDf = thermo.tauQGDf()
Definition at line 55 of file createFields.H.
Referenced by if(), main(), qgdFluxFvPatchScalarField::updateCoeffs(), and qhdFluxFvPatchScalarField::updateCoeffs().
Info<< "Thermo corrected" << endl;autoPtr<compressible::turbulenceModel> turbulence
Definition at line 59 of file createFields.H.
Referenced by forAll(), and main().