QGDsolver: QGDsolver: Foam::fvsc Namespace Reference
Foam::fvsc Namespace Reference
Classes
class fvscStencil
class GaussVolPointBase
class GaussVolPointBase1D
class GaussVolPointBase2D
class GaussVolPointBase3D
class GaussVolPoint
class leastSquaresBase
class leastSquares
class leastSquaresOpt
class reduced
Functions
word fvscOpName (const Foam::fvMesh &mesh, Foam::word termName)
tmp< surfaceVectorField > grad (const volScalarField &vF)
tmp< surfaceVectorField > grad (const tmp< volScalarField > &vF)
tmp< surfaceTensorField > grad (const volVectorField &vF)
tmp< surfaceTensorField > grad (const tmp< volVectorField > &vF)
tmp< surfaceScalarField > div (const volVectorField &vF)
tmp< surfaceScalarField > div (const tmp< volVectorField > &vF)
tmp< surfaceVectorField > div (const volTensorField &vF)
tmp< surfaceVectorField > div (const tmp< volTensorField > &vF)
defineTypeNameAndDebug (fvscStencil, 0)
defineRunTimeSelectionTable (fvscStencil, components)
defineTypeNameAndDebug (GaussVolPoint, 0)
addToRunTimeSelectionTable (fvscStencil, GaussVolPoint, components)
defineTypeNameAndDebug (leastSquares, 0)
addToRunTimeSelectionTable (fvscStencil, leastSquares, components)
defineTypeNameAndDebug (leastSquaresOpt, 0)
addToRunTimeSelectionTable (fvscStencil, leastSquaresOpt, components)
defineTypeNameAndDebug (reduced, 0)
addToRunTimeSelectionTable (fvscStencil, reduced, components)
Function Documentation
Foam::word fvscOpName (const Foam::fvMesh & mesh, Foam::word termName)
Definition at line 43 of file fvsc.C.
Referenced by div(), and grad().
Foam::tmp< Foam::surfaceVectorField > grad (const volScalarField & vF)
Definition at line 59 of file fvsc.C.
References fvscOpName(), fvscStencil::Grad(), and fvscStencil::lookupOrNew().
Referenced by varScModel5::correct(), grad(), if(), and main().
Foam::tmp< Foam::surfaceVectorField > grad (const tmp< volScalarField > & vF)
Definition at line 75 of file fvsc.C.
References grad().
Foam::tmp< Foam::surfaceTensorField > grad (const volVectorField & vF)
Definition at line 81 of file fvsc.C.
References fvscOpName(), fvscStencil::Grad(), and fvscStencil::lookupOrNew().
Foam::tmp< Foam::surfaceTensorField > grad (const tmp< volVectorField > & vF)
Definition at line 95 of file fvsc.C.
References grad().
Foam::tmp< Foam::surfaceScalarField > div (const volVectorField & vF)
Definition at line 101 of file fvsc.C.
References fvscStencil::Div(), fvscOpName(), and fvscStencil::lookupOrNew().
Referenced by div(), if(), and main().
Foam::tmp< Foam::surfaceScalarField > div (const tmp< volVectorField > & vF)
Definition at line 115 of file fvsc.C.
References div().
Foam::tmp< Foam::surfaceVectorField > div (const volTensorField & vF)
Definition at line 121 of file fvsc.C.
References fvscStencil::Div(), fvscOpName(), and fvscStencil::lookupOrNew().
Foam::tmp< Foam::surfaceVectorField > div (const tmp< volTensorField > & vF)
Definition at line 135 of file fvsc.C.
References div().
Foam::fvsc::defineTypeNameAndDebug (fvscStencil , 0)
Foam::fvsc::defineRunTimeSelectionTable (fvscStencil , components)
Foam::fvsc::defineTypeNameAndDebug (GaussVolPoint , 0)
Foam::fvsc::addToRunTimeSelectionTable (fvscStencil , GaussVolPoint , components)
Foam::fvsc::defineTypeNameAndDebug (leastSquares , 0)
Foam::fvsc::addToRunTimeSelectionTable (fvscStencil , leastSquares , components)
Foam::fvsc::defineTypeNameAndDebug (leastSquaresOpt , 0)
Foam::fvsc::addToRunTimeSelectionTable (fvscStencil , leastSquaresOpt , components)
Foam::fvsc::defineTypeNameAndDebug (reduced , 0)
Foam::fvsc::addToRunTimeSelectionTable (fvscStencil , reduced , components)
$mathjax