QGDsolver: particlesQGDFoam/createFields.H File Reference
createFields.H File Reference
Functions
Info<< "Reading thermophysical
properties\n"<< endl;autoPtr
< psiQGDThermo > pThermo (psiQGDThermo::New(mesh))
thermo correct ()
SLGThermo slgThermo (mesh, thermo)
volVectorField U (IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE), mesh)
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE), thermo.rho())
volVectorField rhoU (IOobject("rhoU", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), rho *U)
volScalarField rhoE (IOobject("rhoE", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), rho *e+rho *0.5 *magSqr(U))
volScalarField H (IOobject("Ht", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE),(rhoE+p)/rho)
surfaceScalarField phi ("phi", linearInterpolate(rho *U)&mesh.Sf())
surfaceScalarField phiRhof ("phiRhof", linearInterpolate(rho)*phi)
Switch implicitDiffusion (thermo.implicitDiffusion())
Variables
psiQGDThermo & thermo = pThermo()
volScalarField & e = thermo.he()
volScalarField & p = thermo.p()
const volScalarField & T = thermo.T()
const surfaceScalarField & tauQGDf = thermo.tauQGDf()
const surfaceScalarField & hQGDf = thermo.hQGDf()
const volScalarField & gamma = thermo.gamma()
const volScalarField & psi = thermo.psi()
Info<< "Thermo corrected"
<< endl;autoPtr
< compressible::turbulenceModel > turbulence
Function Documentation
Info<< "Reading thermophysical properties\n" << endl;autoPtr<psiQGDThermo> pThermo (psiQGDThermo:: Newmesh)
thermo correct ()
SLGThermo slgThermo (mesh , thermo)
volVectorField U (IOobject("U", runTime.timeName(), mesh, IOobject::MUST_READ, IOobject::AUTO_WRITE) , mesh)
volScalarField rho (IOobject("rho", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::AUTO_WRITE) , thermo. rho())
volVectorField rhoU (IOobject("rhoU", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE) , rho * U)
Referenced by main().
volScalarField rhoE (IOobject("rhoE", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE) , rho *e+rho *0.5 * magSqrU)
Referenced by main().
volScalarField H (IOobject("Ht", runTime.timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE) , (rhoE+p)/ rho)
surfaceScalarField phi ("phi" , linearInterpolate(rho *U)&mesh.Sf())
surfaceScalarField phiRhof ("phiRhof" , linearInterpolate(rho)* phi)
Switch implicitDiffusion (thermo. implicitDiffusion())
Variable Documentation
psiQGDThermo& thermo = pThermo()
Definition at line 7 of file createFields.H.
volScalarField& e = thermo.he()
Definition at line 12 of file createFields.H.
volScalarField& p = thermo.p()
Definition at line 14 of file createFields.H.
const volScalarField& T = thermo.T()
Definition at line 15 of file createFields.H.
const surfaceScalarField& tauQGDf = thermo.tauQGDf()
Definition at line 17 of file createFields.H.
const surfaceScalarField& hQGDf = thermo.hQGDf()
Definition at line 18 of file createFields.H.
const volScalarField& gamma = thermo.gamma()
Definition at line 19 of file createFields.H.
const volScalarField& psi = thermo.psi()
Definition at line 20 of file createFields.H.
Referenced by main(), Foam::qgdFlux(), and Foam::qgdInterpolate().
Info<< "Thermo corrected" << endl;autoPtr<compressible::turbulenceModel> turbulence
Definition at line 24 of file createFields.H.