QGDsolver: QGDsolver: particlesQGDFoam/updateFields.H File Reference
particlesQGDFoam/updateFields.H File Reference
Variables
rhof = qgdInterpolate(rho)
Uf = qgdInterpolate(U)
rhoUf = qgdInterpolate(rhoU)
rhofUf = rhof*Uf
UrhoUf = qgdInterpolate(U*rhoU)
pf = qgdInterpolate(p)
cf = qgdInterpolate(thermo.c())
gammaf = qgdInterpolate(gamma)
gammam1f = gammaf - 1
Cpf = qgdInterpolate(thermo.Cp())
H = (rhoE + p)/rho
Hf = qgdInterpolate(H)
alphauf = qgdInterpolate(turbulence->alphaEff())
muf = qgdInterpolate(turbulence->muEff())
Variable Documentation
rhof = qgdInterpolate(rho)
Definition at line 8 of file updateFields.H.
Uf = qgdInterpolate(U)
Definition at line 11 of file updateFields.H.
rhoUf = qgdInterpolate(rhoU)
Definition at line 14 of file updateFields.H.
rhofUf = rhof*Uf
Definition at line 15 of file updateFields.H.
UrhoUf = qgdInterpolate(U*rhoU)
Definition at line 18 of file updateFields.H.
pf = qgdInterpolate(p)
Definition at line 21 of file updateFields.H.
Referenced by varScModel6::correct().
cf = qgdInterpolate(thermo.c())
Definition at line 24 of file updateFields.H.
Referenced by if().
gammaf = qgdInterpolate(gamma)
Definition at line 27 of file updateFields.H.
gammam1f = gammaf - 1
Definition at line 28 of file updateFields.H.
Cpf = qgdInterpolate(thermo.Cp())
Definition at line 31 of file updateFields.H.
H = (rhoE + p)/rho
Definition at line 34 of file updateFields.H.
Hf = qgdInterpolate(H)
Definition at line 35 of file updateFields.H.
alphauf = qgdInterpolate(turbulence->alphaEff())
Definition at line 42 of file updateFields.H.
Referenced by if().
muf = qgdInterpolate(turbulence->muEff())
Definition at line 43 of file updateFields.H.
$mathjax