QGDsolver: QGDFoam/QGDFoam.C File Reference
QGDFoam.C File Reference
Solver for unsteady 3D turbulent flow of viscous perfect gas governed by quasi-gas dynamic (QGD) equations at all Mach numbers (from 0.01 to infinity).
Macros
#define NO_CONTROL
Functions
int main (int argc, char *argv[])
Detailed Description
Solver for unsteady 3D turbulent flow of viscous perfect gas governed by quasi-gas dynamic (QGD) equations at all Mach numbers (from 0.01 to infinity).
Original source file QGDFoam.C
QGD system of equations has been developed by scientific group from Keldysh Institute of Applied Mathematics, see http://elizarova.imamod.ru/selection-of-papers.html
A comprehensive description of QGD equations and their applications can be found here:
Elizarova, T.G.
"Quasi-Gas Dynamic equations"
Springer, 2009
A brief of theory on QGD and QHD system of equations:
Elizarova, T.G. and Sheretov, Y.V.
"Theoretical and numerical analysis of quasi-gasdynamic and quasi-hydrodynamic
equations"
J. Computational Mathematics and Mathematical Physics, vol. 41, no. 2, pp 219-234,
2001
Developed by UniCFD group (www.unicfd.ru) of ISP RAS (www.ispras.ru).
Definition in file QGDFoam.C.
Macro Definition Documentation
#define NO_CONTROL
Function Documentation
int main (int argc, char * argv[])
——–Start———
——–End———
——–Start———
——–End———
——–Start———
——–End———
——–Start———
——–End——— # 70 "/home/cfd/4jenk/digitef-dev-1912-1/QGDFoam/QGDFoam.C" 2 #include "createTimeControls.H" #include "createFvOptions.H"
* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //
Courant numbers used to adjust the time-step scalar CoNum = 0.0; scalar meanCoNum = 0.0;
Info<< "\nStarting time loop\n" << endl;
while (runTime.run()) { /*
Update QGD viscosity
——–Start———
——–End———
——–Start———
——–End———
——–Start———
——–End———
——–Start———
——–End——— # 103 "/home/cfd/4jenk/digitef-dev-1912-1/QGDFoam/QGDFoam.C" 2
/*
Update time step
– Solve energy
Definition at line 60 of file QGDFoam.C.
References e, p, psi, rho(), rhoE(), rhoU(), thermo, turbulence, and U().