QGDsolver: QGDsolver: QGD/QGDcommon/QGDUEqn.H File Reference
QGD/QGDcommon/QGDUEqn.H File Reference
Functions
solve (fvm::ddt(rhoU)+fvc::div(phiJmU)+fvc::div(phiP)-fvc::div(phiPi))
U ref ()
U correctBoundaryConditions ()
if (implicitDiffusion)
Function Documentation
solve (fvm:: ddtrhoU)+fvc::div(phiJmU)+fvc::div(phiP)-fvc::div(phiPi)
U ref ()
U correctBoundaryConditions ()
if (implicitDiffusion)
Definition at line 50 of file QGDUEqn.H.
References Foam::fvsc::div(), Foam::fvsc::grad(), muf, phiSigmaDotU(), phiTauMC, rho(), rhoU(), rhoUSu(), sigmaDotUPtr, solve(), tauMCPtr, U(), and Uf.
$mathjax