QGDsolver: QGD/QGDcommon/QGDYEqn.H File Reference
QGDYEqn.H File Reference
Functions
volScalarField Yt (0.0 *Y[0])
forAll (Y, i)
Variables
Qdot = combustion->Qdot()
Function Documentation
volScalarField Yt (0.0 * Y[0])
Referenced by forAll().
forAll (Y , i)
Definition at line 6 of file QGDYEqn.H.
References combustion(), composition, diffusiveFlux(), Foam::fvsc::div(), implicitDiffusion(), inertIndex(), muf, phiJmY(), rho(), ScNumbers(), solve(), Y, and Yt().
Referenced by GaussVolPointBase3D::calcDivfBF(), GaussVolPointBase3D::calcDivfIF(), GaussVolPointBase3D::calcGradfBF(), GaussVolPointBase3D::calcGradfIF(), leastSquaresBase::calculateWeights(), leastSquares::Div(), leastSquaresOpt::Div(), GaussVolPointBase2D::faceDiv(), GaussVolPointBase2D::faceGrad(), leastSquaresOpt::faceScalarDer(), leastSquaresBase::findNeighbours(), forAll(), formVfValues(), GaussVolPointBase2D::GaussVolPointBase2D(), GaussVolPointBase3D::GaussVolPointBase3D(), leastSquares::Grad(), leastSquaresOpt::Grad(), main(), GaussVolPointBase3D::quaCalcWeights(), and GaussVolPointBase3D::triCalcWeights().
Variable Documentation
Qdot = combustion->Qdot()
Definition at line 3 of file QGDYEqn.H.
Referenced by main().