QGDsolver: QGD/QGDcommon/QHDTEqn.H File Reference
QHDTEqn.H File Reference
Solver for unsteady 3D turbulent flow of incompressible fluid governed by quasi-hydrodynamic dynamic (QHD) equations.
Functions
if (implicitDiffusion)
Variables
surfaceScalarField phiTauTReg = tauQGDf*phiu*(Uf & gradTf)
else
Detailed Description
Solver for unsteady 3D turbulent flow of incompressible fluid governed by quasi-hydrodynamic dynamic (QHD) equations.
Original source file QHDTEqn.H
QHD system of equations has been developed by scientific group from Keldysh Institute of Applied Mathematics, see http://elizarova.imamod.ru/selection-of-papers.html
A comprehensive description of QGD equations and their applications can be found here:
Elizarova, T.G.
"Quasi-Gas Dynamic equations"
Springer, 2009
A brief of theory on QGD and QHD system of equations:
Elizarova, T.G. and Sheretov, Y.V.
"Theoretical and numerical analysis of quasi-gasdynamic and quasi-hydrodynamic
equations"
J. Computational Mathematics and Mathematical Physics, vol. 41, no. 2, pp 219-234,
2001
Developed by UniCFD group (www.unicfd.ru) of ISP RAS (www.ispras.ru).
Definition in file QHDTEqn.H.
Function Documentation
if (implicitDiffusion)
Definition at line 60 of file QHDTEqn.H.
References gradTf, implicitDiffusion(), phi, phiTauTReg, phiTf(), phiu, Foam::qgdFlux(), solve(), T, tauQGDf, Tf, and Uf.
Variable Documentation
surfaceScalarField phiTauTReg = tauQGDf*phiu*(Uf & gradTf)
Definition at line 57 of file QHDTEqn.H.
Referenced by if(), and main().
else
Initial value:
{
        solve
        (
            fvm::ddt(T)
          + fvc::div(phiTf)
          - fvc::laplacian(Hif,T)
          - fvc::div(phiTauTReg)
          ==
          TSu
        )
Definition at line 73 of file QHDTEqn.H.