QGDsolver: reactingLagrangianQGDFoam/reactingLagrangianQGDFoam.C File Reference
reactingLagrangianQGDFoam.C File Reference
Solver for unsteady 3D turbulent flow of perfect gas governed by quasi-gas dynamic (QGD) equations at all Mach numbers (from 0 to infinity) coupled with chemistry reactions.
Macros
#define NO_CONTROL
Functions
int main (int argc, char *argv[])
Detailed Description
Solver for unsteady 3D turbulent flow of perfect gas governed by quasi-gas dynamic (QGD) equations at all Mach numbers (from 0 to infinity) coupled with chemistry reactions.
Original source file reactingLagrangianQGDFoam.C
QGD system of equations has been developed by scientific group from Keldysh Institute of Applied Mathematics, see http://elizarova.imamod.ru/selection-of-papers.html
Developed by UniCFD group (www.unicfd.ru) of ISP RAS (www.ispras.ru).
Definition in file reactingLagrangianQGDFoam.C.
Macro Definition Documentation
#define NO_CONTROL
Function Documentation
int main (int argc, char * argv[])
——–Start———
——–End———
——–Start———
——–End———
——–Start———
——–End———
——–Start———
——–End———
——–Start———
——–End———
——–Start———
——–End———
——–Start———
——–End———
——–Start———
——–End——— # 90 "/home/jenkins/workspace/experQGDsolver-8doxigen/QGDsolver/reactingLagrangianQGDFoam/reactingLagrangianQGDFoam.C" 2
/*
Update time step
– Solve energy
Definition at line 46 of file reactingLagrangianQGDFoam.C.
References e, forAll(), p, psi, Qdot, rho(), rhoE(), rhoESu(), rhoU(), rhoUSu(), T, thermo, turbulence, U(), and Y.