#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

touch JetH2.foam
runApplication blockMesh
runApplication decomposePar -force
runApplication mpirun -np 4 snappyHexMesh -overwrite  -parallel
runApplication reconstructParMesh -constant -mergeTol 1e-6

rm -rf log.decomposePar
rm -rf log.mpirun

runApplication decomposePar -force
runApplication mpirun -np 4 reactingQGDFoam  -parallel

#------------------------------------------------------------------------------
