#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

touch shockTube_Sod_RS.foam
runApplication blockMesh
runApplication setFields
runApplication `getApplication`

#------------------------------------------------------------------------------
