#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

libfile=`ls $FOAM_USER_LIBBIN/libcompressibleTools.so &>/dev/null`
if [ $?  -ne 0 ]
then
    echo "compressibleTools library not found"
    echo "Install the library before running this tutorial"
    echo "Library can be downloaded from https://github.com/unicfdlab/libcompressibleTools"
    exit 1
fi

rm -rf 0
cp -rf 0.orig/ 0/

runApplication blockMesh
runApplication `getApplication`

#------------------------------------------------------------------------------
